//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/_UIDatePickerView.h>

@class NSDateComponents;

@interface _UIDatePickerView (_UIDatePickerViewDeprecated)
- (int)second;
- (int)minute;
- (int)hour;
@property(copy, nonatomic) NSDateComponents *dateComponents; // @dynamic dateComponents;
@property(nonatomic) _Bool staggerTimeIntervals; // @dynamic staggerTimeIntervals;
@end

