//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UILabel;

__attribute__((visibility("hidden")))
@interface _UIDictionaryDownloadConfirmView : UIView
{
    UILabel *_downloadRequestLabel;
    NSString *_downloadRequestText;
    UIButton *_downloadButton;
}

@property(readonly, nonatomic) UIButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(copy, nonatomic) NSString *downloadRequestText; // @synthesize downloadRequestText=_downloadRequestText;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

