//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIWebViewDelegate.h"

@class NSArray, NSURL, UIColor;

__attribute__((visibility("hidden")))
@interface _UIDefinitionService : NSObject <UIWebViewDelegate>
{
    NSArray *_dictionaries;
    id <_UIDefinitionServiceDelegate> _delegate;
    UIColor *_backgroundColor;
    NSURL *_stylesheetURL;
}

+ (id)foregroundColor;
+ (id)backgroundColor;
@property(readonly, nonatomic) NSURL *stylesheetURL; // @synthesize stylesheetURL=_stylesheetURL;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) id <_UIDefinitionServiceDelegate> delegate; // @synthesize delegate=_delegate;
- (unsigned int)languageDirectionForString:(id)arg1;
- (id)markupForString:(id)arg1;
- (BOOL)hasMarkupForString:(id)arg1;
- (id)_dictionaryForString:(id)arg1;
- (void)dealloc;
- (id)init;

@end

