//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSSet;

@interface _UIFenceController : NSObject
{
    unsigned int _fenceBase;
    unsigned int _fenceOffset;
    NSSet *_fencedWindows;
}

+ (id)sharedFenceController;
- (void)fenceAllApplicationWindows;
- (id)_fenceableWindows;
- (unsigned int)_fenceWindows:(id)arg1 additionalWindows:(int)arg2;
- (void)_fenceCompleted;
- (id)init;

@end

