//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIImage;

__attribute__((visibility("hidden")))
@interface _UIImageViewExtendedStorage : NSObject
{
    BOOL _highlighted;
    UIImage *_image;
    UIImage *_highlightedImage;
    NSArray *_animationImages;
    NSArray *_highlightedAnimationImages;
    double _animationDuration;
    int _animationRepeatCount;
    int _drawMode;
}

- (void)dealloc;

@end

