//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/_UIQueueRedirectingProxy.h>

#import "XPCProxyTarget.h"

@interface _UIQueueRedirectingProxy (XPCProxyTargetSupport) <XPCProxyTarget>
- (id)proxy:(id)arg1 detailedSignatureForSelector:(SEL)arg2;
@end

