//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/_UIRemoteViewController.h>

#import "XPCProxyTarget.h"

@interface _UIRemoteViewController (Protected) <XPCProxyTarget>
+ (id)exportedInterface;
+ (id)serviceViewControllerInterface;
+ (_Bool)shouldPropagateAppearanceCustomizations;
- (id)proxy:(id)arg1 detailedSignatureForSelector:(SEL)arg2;
- (id)serviceViewControllerProxyWithErrorHandler:(CDUnknownBlockType)arg1;
- (id)serviceViewControllerProxy;
- (void)viewServiceSupportedInterfaceOrientationsDidChange;
- (void)viewServiceDidTerminateWithError:(id)arg1;
@end

