//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSObject<OS_dispatch_queue>, NSString, _UIAsyncInvocation;

__attribute__((visibility("hidden")))
@interface _UIRemoteViewControllerConnectionRequest : NSObject
{
    CDUnknownBlockType _handler;
    NSString *_viewServiceBundleIdentifier;
    NSString *_viewControllerClassName;
    BOOL _propagateAppearanceCustomizations;
    _UIAsyncInvocation *_cancelInvocationForCurrentOperation;
    CDStruct_5a8e6190 _connectionInfo;
    NSObject<OS_dispatch_queue> *_queue;
    BOOL _isCancelledOrComplete;
    NSError *_error;
    _UIAsyncInvocation *_requestCancellationInvocation;
}

+ (id)requestViewController:(id)arg1 fromServiceWithBundleIdentifier:(id)arg2 propagateAppearanceCustomizations:(BOOL)arg3 connectionHandler:(CDUnknownBlockType)arg4;
- (id)_cancelWithError:(id)arg1;
- (void)_didFinishEstablishingConnection;
- (void)_connectToServiceViewController;
- (void)_sendServiceTextEffectsRequest;
- (void)_connectToTextEffectsOperator;
- (void)_sendServiceViewControllerRequest;
- (void)_connectToViewControllerOperator;
- (void)_connectToViewService;
- (void)_cancelUnconditionallyThen:(CDUnknownBlockType)arg1;
- (void)dealloc;

@end

