//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CUICatalog, NSBundle, NSString, UIImage;

@protocol _UISharedArtworkResolving <NSObject>
- (void)setPreferredScale:(double)arg1;
- (UIImage *)imageNamed:(NSString *)arg1 idiom:(long long)arg2;
- (UIImage *)imageNamed:(NSString *)arg1;

@optional
- (CUICatalog *)_catalog;
- (NSString *)nameAtIndex:(unsigned long long)arg1;
- (id)initWithName:(NSString *)arg1 inBundle:(NSBundle *)arg2 idiom:(long long)arg3;
@end

