//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface _UIStatusBarOrientationStackInfo : NSObject
{
    int _hostPID;
    int _statusBarOrientationWithoutHost;
}

@property int statusBarOrientationWithoutHost; // @synthesize statusBarOrientationWithoutHost=_statusBarOrientationWithoutHost;
@property int hostPID; // @synthesize hostPID=_hostPID;

@end

