//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIImage;

__attribute__((visibility("hidden")))
@interface _UIToolbarAppearanceStorage : NSObject
{
    UIImage *backgroundImage;
    UIImage *miniBackgroundImage;
    UIImage *topBackgroundImage;
    UIImage *miniTopBackgroundImage;
}

@property(retain, nonatomic) UIImage *miniTopBackgroundImage; // @synthesize miniTopBackgroundImage;
@property(retain, nonatomic) UIImage *topBackgroundImage; // @synthesize topBackgroundImage;
@property(retain, nonatomic) UIImage *miniBackgroundImage; // @synthesize miniBackgroundImage;
@property(retain, nonatomic) UIImage *backgroundImage; // @synthesize backgroundImage;
- (void)dealloc;

@end

