//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface _UITableViewCellSeparatorView : UIView
{
    _Bool _drawsWithVibrantMode;
    UIView *_backgroundView;
    UIView *_overlayView;
}

@property(nonatomic) _Bool drawsWithVibrantMode; // @synthesize drawsWithVibrantMode=_drawsWithVibrantMode;
- (void)dealloc;

@end

