//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSXPCListenerDelegate.h"

@class NSMutableArray, NSXPCListener;

__attribute__((visibility("hidden")))
@interface _UIViewServiceSessionManager : NSObject <NSXPCListenerDelegate>
{
    int _lock;
    NSXPCListener *_listener;
    NSMutableArray *_sessions;
    int _connectionNotificationToken;
}

+ (_Bool)hasActiveSessions;
+ (void)startViewServiceSessionManager;
+ (_Bool)_shouldUseXPCObjects;
- (void)_startOrStopSystemsForBackgroundRunning;
- (_Bool)listener:(id)arg1 shouldAcceptNewConnection:(id)arg2;
- (_Bool)_hasActiveSessions;
- (void)_registerSessionForDefaultDeputies:(id)arg1;
- (void)_startListener;
- (id)_init;
- (void)dealloc;
- (id)init;

@end

