//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSArray, NSString, NSValue, XPCMachSendRight;

@protocol _UIViewServiceViewControllerOperator_RemoteViewControllerInterface
- (void)__dimmingViewWasTapped;
- (void)__textServiceDidDismiss;
- (void)__hostDidUpdateAppearanceWithSerializedRepresentations:(NSArray *)arg1 originalSource:(id)arg2;
- (void)__alertIsDisappearing:(NSString *)arg1;
- (void)__alertIsAppearing:(NSString *)arg1 withFrameValue:(NSValue *)arg2;
- (void)__scrollToTopFromTouchAtViewLocation:(NSValue *)arg1 resultHandler:(void (^)(id, NSError *))arg2;
- (void)__hostedActionSheetDidDismissWithClickedButtonIndex:(int)arg1;
- (void)__hostedActionSheetClickedButtonAtIndex:(int)arg1;
- (void)__hostedActionSheetDidPresent;
- (void)__hostDidPromoteFirstResponder;
- (void)__hostDidRotateFromInterfaceOrientation:(int)arg1 skipSelf:(BOOL)arg2;
- (void)__hostWillAnimateRotationToInterfaceOrientation:(int)arg1 duration:(double)arg2 skipSelf:(BOOL)arg3;
- (void)__hostWillRotateToInterfaceOrientation:(int)arg1 duration:(double)arg2 skipSelf:(BOOL)arg3;
- (void)__hostDidChangeStatusBarOrientationToInterfaceOrientation:(int)arg1;
- (void)__hostDidEnterBackground;
- (void)__hostWillEnterForeground;
- (void)__setContentSize:(NSValue *)arg1;
- (void)__setServiceInPopover:(BOOL)arg1;
- (void)__hostViewDidDisappear:(BOOL)arg1;
- (void)__hostViewWillDisappear:(BOOL)arg1;
- (void)__hostViewDidAppear:(BOOL)arg1;
- (void)__hostViewWillAppear:(BOOL)arg1 inInterfaceOrientation:(int)arg2 completionHandler:(void (^)(id, NSError *))arg3;
- (void)__hostReadyToReceiveMessagesFromServiceViewController;
- (void)__createViewController:(NSString *)arg1 withAppearanceSerializedRepresentations:(NSArray *)arg2 hostAccessibilityServerPort:(XPCMachSendRight *)arg3 canShowTextServices:(BOOL)arg4 replyHandler:(void (^)(id, NSError *))arg5;
@end

