//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (UIStringDrawingPrivate)
- (struct CGSize)drawComponentsJoinedByString:(id)arg1 atPoint:(struct CGPoint)arg2 forWidth:(float)arg3 withFont:(id)arg4 lineBreakMode:(int)arg5;
- (struct CGSize)sizeOfComponentsJoinedByString:(id)arg1 withFont:(id)arg2 forWidth:(float)arg3 lineBreakMode:(int)arg4;
- (struct CGSize)_drawComponentsJoinedByString:(id)arg1 atPoint:(struct CGPoint *)arg2 forWidth:(float)arg3 withFont:(id)arg4 lineBreakMode:(int)arg5;
@end

