//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSArray.h"

@interface NSArray (UIKBExtras)
- (struct _NSRange)rangeWithStartIndex:(int)arg1 endIndex:(int)arg2;
- (id)intersectionWithArray:(id)arg1;
- (struct _NSRange)_rangeWithStartIndex:(int)arg1 endIndex:(int)arg2;
- (id)_intersectionWithArray:(id)arg1;
- (BOOL)_kb_firstObjectsEqual:(unsigned int)arg1;
- (BOOL)_kb_firstTwoObjectsEqual;
- (id)_kb_firstObject;
@end

