//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (_UIKeyboardEmojiAdditions)
- (id)_asUnicodeHex;
- (id)_stringWithSoftBankEmojiCodePoints;
- (id)_stringWithPublicEmojiCodePoints;
@end

