//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIAlertView.h>

@interface UIAlertView (ViewServiceSupport)
+ (id)_alertViewForWindow:(id)arg1;
+ (id)_alertViewForSessionWithRemoteViewController:(id)arg1;
+ (id)_remoteAlertViewWithBlock:(CDUnknownBlockType)arg1;
@end

