//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIAnimation.h>

@interface UIAnimation (Internal)
- (void)markStop;
- (void)markStart:(double)arg1;
- (float)fractionForTime:(double)arg1;
- (void)setDuration:(double)arg1;
- (BOOL)tvOutput;
- (int)state;
@end

