//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIApplication.h>

@interface UIApplication (UIApplicationTesting)
- (void)setDeviceOrientation:(int)arg1;
- (void)rotateIfNeeded:(long long)arg1 completion:(CDUnknownBlockType)arg2;
- (_Bool)rotateIfNeeded:(long long)arg1;
- (void)testPrep:(id)arg1 options:(id)arg2;
- (void)stopLeaking;
- (void)startLeaking;
- (void)_leak;
- (void)enableFramebufferStatisticsGathering;
- (void)stopCHUDRecording;
- (void)startCHUDRecording:(id)arg1;
- (long long)_testOrientation:(id)arg1 options:(id)arg2;
- (_Bool)handleTestURL:(id)arg1;
- (void)failedTest:(id)arg1 withResults:(id)arg2;
- (void)failedTest:(id)arg1;
- (void)finishedTest:(id)arg1 waitForCommit:(_Bool)arg2 extraResults:(id)arg3 withTeardownBlock:(CDUnknownBlockType)arg4;
- (void)finishedTest:(id)arg1 waitForCommit:(_Bool)arg2 extraResults:(id)arg3;
- (void)finishedTest:(id)arg1 extraResults:(id)arg2 waitForNotification:(id)arg3;
- (void)finishedTest:(id)arg1 extraResults:(id)arg2 withTeardownBlock:(CDUnknownBlockType)arg3;
- (void)finishedTest:(id)arg1 extraResults:(id)arg2;
- (void)finishedTest:(id)arg1;
- (void)finishedTest:(id)arg1 extraResults:(id)arg2 waitForNotification:(id)arg3 withTeardownBlock:(CDUnknownBlockType)arg4;
- (void)_reportResults:(id)arg1;
- (struct __CFMessagePort *)_purplePPTServerPort;
- (void)finishedIPTest:(id)arg1 extraResults:(id)arg2;
- (void)finishedIPTest:(id)arg1;
- (void)startedIPTest:(id)arg1;
- (_Bool)isPPTAvailable;
- (void)_sendDictionaryToPPT:(id)arg1;
- (void)finishedSubTest:(id)arg1 forTest:(id)arg2;
- (void)startedSubTest:(id)arg1 forTest:(id)arg2 withMetrics:(id)arg3;
- (void)startedSubTest:(id)arg1 forTest:(id)arg2;
- (id)subTest:(id)arg1 ForTest:(id)arg2 withMetrics:(id)arg3;
- (id)resultsForTest:(id)arg1;
- (void)startedTest:(id)arg1;
- (id)_currentFrameCountForTestDisplay;
- (_Bool)isRunningSuspendTest;
- (_Bool)isRunningQuitTest;
- (_Bool)isRunningTest:(id)arg1;
- (_Bool)isRunningTest;
- (_Bool)shouldRecordExtendedLaunchTime;
- (void *)_getSymbol:(id)arg1 forFramework:(id)arg2;
- (id)_pathForFrameworkName:(id)arg1 inPrivate:(_Bool)arg2;
- (_Bool)reportApplicationSuspended;
- (void)runTest:(id)arg1 startingBeforeAnimation:(id)arg2 stoppingAfterAnimation:(id)arg3;
- (void)runTest:(id)arg1 forAnimation:(id)arg2;
- (void)_noteAnimationFinished:(id)arg1;
- (void)_noteAnimationStarted:(id)arg1;
- (void)installCACommitCompletionBlock:(CDUnknownBlockType)arg1;
- (_Bool)runTest:(id)arg1 options:(id)arg2;
- (id)_currentTests;
- (_Bool)launchedToTest;
@end

