//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIApplication.h>

@interface UIApplication (UIApplicationKeyboardTesting)
- (void)runTestForKeyboardSplitAndMergeWithName:(id)arg1 withShowKeyboardBlock:(CDUnknownBlockType)arg2 withExtraResultsBlock:(CDUnknownBlockType)arg3 withCleanupBlock:(CDUnknownBlockType)arg4;
- (void)runTestForKeyboardRotationWithName:(id)arg1 fromOrientation:(long long)arg2 withShowKeyboardBlock:(CDUnknownBlockType)arg3 withExtraResultsBlock:(CDUnknownBlockType)arg4 withCleanupBlock:(CDUnknownBlockType)arg5;
- (void)runTestForKeyboardBringupAndDismissalWithName:(id)arg1 withShowKeyboardBlock:(CDUnknownBlockType)arg2 withHideKeyboardBlock:(CDUnknownBlockType)arg3 withExtraResultsBlock:(CDUnknownBlockType)arg4 withCleanupBlock:(CDUnknownBlockType)arg5;
- (void)_runSubTestForKeyboardMergeWithName:(id)arg1 withExtraResultsBlock:(CDUnknownBlockType)arg2 withCleanupBlock:(CDUnknownBlockType)arg3;
- (void)_runSubTestForKeyboardSplitWithName:(id)arg1 withShowKeyboardBlock:(CDUnknownBlockType)arg2 withExtraResultsBlock:(CDUnknownBlockType)arg3 withCleanupBlock:(CDUnknownBlockType)arg4;
- (void)_runSubTestForKeyboardDismissalWithName:(id)arg1 withHideKeyboardBlock:(CDUnknownBlockType)arg2 withExtraResultsBlock:(CDUnknownBlockType)arg3 withCleanupBlock:(CDUnknownBlockType)arg4;
- (void)_runSubTestForKeyboardBringupWithName:(id)arg1 withShowKeyboardBlock:(CDUnknownBlockType)arg2 withHideKeyboardBlock:(CDUnknownBlockType)arg3 withExtraResultsBlock:(CDUnknownBlockType)arg4 withCleanupBlock:(CDUnknownBlockType)arg5;
- (void)showKeyboardUsingBlock:(CDUnknownBlockType)arg1 withCompletionBlock:(CDUnknownBlockType)arg2;
- (void)installNotificationObserverForNotificationName:(id)arg1 forOneNotification:(_Bool)arg2 usingBlock:(CDUnknownBlockType)arg3;
@end

