//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIFont;

__attribute__((visibility("hidden")))
@interface UIAutocorrectStringView : UIView
{
    NSString *m_string;
    UIFont *m_font;
}

- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 string:(id)arg2 font:(id)arg3;

@end

