//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIBarButtonItem.h>

@interface UIBarButtonItem (UIInternal)
- (void)_sendAction:(id)arg1 withEvent:(id)arg2;
- (_Bool)isCustomViewItem;
- (void)setIsMinibarView:(_Bool)arg1;
- (_Bool)isMinibarView;
- (id)view;
- (void)setView:(id)arg1;
- (id)nextResponder;
- (id)window;
@end

