//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIBarButtonItem.h>

@class UIImage, UIToolbarButton;

@interface UIBarButtonItem (UIBarButtonItemPrivate)
- (float)_width;
- (void)_setWidth:(float)arg1;
- (id)createViewForToolbar:(id)arg1;
- (id)createViewForNavigationItem:(id)arg1;
- (void)_applyPositionAdjustmentToSegmentedControl:(id)arg1;
- (BOOL)_shouldBezelSystemButtonImage;
@property(nonatomic, setter=_setImageHasEffects:) BOOL _imageHasEffects;
@property(readonly, nonatomic) UIToolbarButton *_toolbarButton;
@property(nonatomic, getter=_miniImageInsets, setter=_setMiniImageInsets:) struct UIEdgeInsets miniImageInsets;
@property(retain, nonatomic, getter=_miniImage, setter=_setMiniImage:) UIImage *miniImage;

// Remaining properties
@property(nonatomic, getter=isEnabled) BOOL enabled;
@property(readonly, nonatomic) BOOL isSystemItem;
@property(nonatomic) BOOL selected;
@property(readonly, nonatomic) int systemItem;
@end

