//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@interface UIButton (UIButtonInternal)
- (void)_titleAttributesChanged;
- (int)_buttonType;
- (void)_setButtonType:(int)arg1;
- (void)_setupTitleView;
- (void)_setupImageView;
- (id)_setupBackgroundView;
@end

