//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface UICalloutBarOverlay : UIView
{
    struct CGRect m_arrowRect;
    float m_dividerOffsets[20];
    BOOL highlighted;
    struct CGRect highlightRect;
}

@property(nonatomic) struct CGRect highlightRect; // @synthesize highlightRect;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted;
- (void)setHighlighted:(BOOL)arg1 forFrame:(struct CGRect)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)setDividerOffsets:(float *)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

