//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (UIColorSystemColorsPrivate)
+ (id)_alternateForegroundColor2;
+ (id)_alternateForegroundColor;
+ (id)_alternateTextColor2;
+ (id)_alternateTextColor;
+ (id)_alternateBackgroundColor2;
+ (id)_alternateBackgroundColor;
+ (id)_webContentBackgroundColor;
+ (id)_systemSelectedColor;
+ (id)_externalBarBackgroundColor;
+ (id)_alternateGrayColorForFontSize:(double)arg1;
+ (id)_grayColorForFontSize:(double)arg1;
+ (id)_alternateSystemInteractionTintColor;
+ (id)_dimmingViewColor;
+ (id)_translucentPaperTextureColor;
+ (id)noContentDarkGradientBackgroundColor;
+ (id)noContentLightGradientBackgroundColor;
+ (id)_accessibilityButtonShapesNoBlendModeBackgroundColorOnDark;
+ (id)_accessibilityButtonShapesNoBlendModeBackgroundColorOnLight;
+ (id)_accessibilityButtonShapesDisabledBackgroundColorOnDark;
+ (id)_accessibilityButtonShapesBackgroundColorOnDark;
+ (id)_accessibilityButtonShapesBackgroundColorOnLight;
+ (id)_externalSystemSuperDarkGrayColor;
+ (id)_externalSystemExtraDarkGrayColor;
+ (id)_externalSystemDarkGrayColor;
+ (id)_externalSystemGrayColor;
+ (id)_externalSystemMidGrayColor;
+ (id)_externalSystemWhiteColor;
+ (id)_systemMidGrayTintColor;
+ (id)_barStyleBlackHairlineShadowColor;
+ (id)_barHairlineShadowColor;
+ (id)_systemDestructiveTintColor;
+ (id)_systemInteractionTintColor;
@end

