//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableIndexSet, UICollectionViewData;

__attribute__((visibility("hidden")))
@interface UICollectionViewUpdate : NSObject
{
    NSArray *_updateItems;
    UICollectionViewData *_oldModel;
    UICollectionViewData *_newModel;
    struct CGRect _oldVisibleBounds;
    struct CGRect _newVisibleBounds;
    NSMutableIndexSet *_movedItems;
    NSMutableIndexSet *_movedSections;
    NSMutableArray *_deletedSections;
    NSMutableArray *_insertedSections;
    int *_oldSectionMap;
    int *_newSectionMap;
    int *_oldGlobalItemMap;
    int *_newGlobalItemMap;
    id *_animatedItems;
    id *_animatedHeaders;
    id *_animatedFooters;
    NSMutableArray *_viewAnimations;
    NSMutableArray *_gaps;
}

- (void)_computeGaps;
- (void)_computeItemUpdates;
- (void)_computeSectionUpdates;
- (void)dealloc;
- (id)initWithUpdateItems:(id)arg1 oldModel:(id)arg2 newModel:(id)arg3 oldVisibleBounds:(struct CGRect)arg4 newVisibleBounds:(struct CGRect)arg5;

@end

