//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UICollectionView.h>

@interface UICollectionView (StateRestoration)
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (_Bool)_indexPathIsValid:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
@end

