//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (UIColorSystemColorsPrivate)
+ (id)_webContentBackgroundColor;
+ (id)_systemSelectedColor;
+ (id)_grayColorForFontSize:(double)arg1;
+ (id)_dimmingViewColor;
+ (id)_translucentPaperTextureColor;
+ (id)noContentDarkGradientBackgroundColor;
+ (id)noContentLightGradientBackgroundColor;
+ (id)_systemMidGrayTintColor;
+ (id)_barStyleBlackHairlineShadowColor;
+ (id)_barHairlineShadowColor;
+ (id)_alternateSystemInteractionTintColor;
+ (id)_systemDestructiveTintColor;
+ (id)_systemInteractionTintColor;
@end

