//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIContinuation.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface UIContinuation : NSObject <UIContinuation>
{
    NSMutableDictionary *_properties;
    id _continuationContext;
    id _continuationTarget;
    SEL _continuationSelector;
}

- (void)doContinuation;
- (id)valueForProperty:(id)arg1;
- (void)setValue:(id)arg1 forProperty:(id)arg2;
- (void)dealloc;
- (id)context;
- (id)initWithTarget:(id)arg1 context:(id)arg2 continuationSelector:(SEL)arg3;

@end

