//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSTimer, UITextRange;

__attribute__((visibility("hidden")))
@interface UIDictationLandingView : UIView
{
    int _highlighted;
    float _diameter;
    NSTimer *_timer;
    UITextRange *_range;
    id _placeholder;
    BOOL _willInsertText;
}

+ (id)sharedInstance;
@property(nonatomic) BOOL willInsertText; // @synthesize willInsertText=_willInsertText;
- (void)stopLanding;
- (void)startLanding;
- (void)advanceLanding:(id)arg1;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

