//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UITextFieldDelegate.h"

@class NSObject<UIDocumentPasswordViewDelegate>, UIImageView, UILabel, UITextField;

__attribute__((visibility("hidden")))
@interface UIDocumentPasswordView : UIView <UITextFieldDelegate>
{
    UIImageView *_iconView;
    UITextField *_passwordTextField;
    UILabel *_label;
    UILabel *_errorLabel;
    NSObject<UIDocumentPasswordViewDelegate> *passwordDelegate;
}

@property(readonly, nonatomic) UITextField *passwordField; // @synthesize passwordField=_passwordTextField;
@property(nonatomic) NSObject<UIDocumentPasswordViewDelegate> *passwordDelegate; // @synthesize passwordDelegate;
- (void)_passwordEntered:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (struct CGRect)_iconRectForWidth:(float)arg1;
- (void)dealloc;
- (id)initWithDocumentName:(id)arg1;

@end

