//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIEvent.h>

@interface UIEvent (UIEventInternal)
- (double)_wheelVelocity;
- (_Bool)isKeyDown;
- (void)_sendEventToResponder:(id)arg1;
- (id)_windows;
- (id)_screen;
- (void)_setTimestamp:(double)arg1;
- (id)_init;
@end

