//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UITouch;

__attribute__((visibility("hidden")))
@interface UIGestureContext : NSObject
{
    struct CGPoint _startLocation;
    float _startTimestamp;
    struct CGPoint _currentLocation;
    UITouch *_touch;
    int _state;
}

@property(nonatomic) float startTimestamp; // @synthesize startTimestamp=_startTimestamp;
@property(nonatomic) int state; // @synthesize state=_state;
@property(retain, nonatomic) UITouch *touch; // @synthesize touch=_touch;
@property(nonatomic) struct CGPoint currentLocation; // @synthesize currentLocation=_currentLocation;
@property(nonatomic) struct CGPoint startLocation; // @synthesize startLocation=_startLocation;
- (id)initWithTouch:(id)arg1 inView:(id)arg2;

@end

