//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSIndexSet;

@interface UIGroupDeletionItem : NSObject
{
    unsigned int _lastIndex;
    int _group;
    NSIndexSet *_indexes;
}

- (void)setLastIndex:(unsigned int)arg1;
- (unsigned int)lastIndex;
- (id)indexes;
- (int)group;
- (void)dealloc;
- (id)initWithIndexes:(id)arg1 inGroup:(int)arg2;
- (id)initWithGroup:(int)arg1 andIndexes:(id)arg2;
- (id)initWithGroup:(int)arg1;

@end

