//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface UIImageView (Pretiling)
- (id)_cachedPretiledImageForImage:(id)arg1;
- (void)_clearPretiledImageCacheForImage:(id)arg1;
- (void)_updatePretiledImageCacheForImage:(id)arg1;
- (_Bool)_recomputePretilingState;
@end

