//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (TabBarItemImages)
- (id)_unselectedTabBarItemImageWithTintColor:(id)arg1;
- (id)_selectedTabBarItemImageWithTintColor:(id)arg1;
@end

