//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

@interface UIImageView (UIImageViewInternal)
- (void)_updateState;
- (BOOL)_setImageViewContents:(id)arg1;
- (BOOL)_canDrawContent;
- (BOOL)_shouldDrawImage:(id)arg1;
- (void)setContentStretch:(struct CGRect)arg1;
@end

