//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface UIInputSwitcherTableCellBackgroundView : UIView
{
    BOOL m_selected;
}

@property(nonatomic) BOOL selected; // @synthesize selected=m_selected;
- (void)drawRect:(struct CGRect)arg1;

@end

