//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKBRenderFactory.h>

@interface UIKBRenderFactory (UIKBRenderFactory_Passcode)
- (id)extraPasscodePaddleTraits;
- (id)passcodeShiftedControlKeyTraits;
- (id)passcodeActiveControlKeyTraits;
- (id)passcodeControlKeyTraits;
- (id)passcodeKeyEdgeColorName;
- (double)passcodeEdgeWeight;
- (id)passcodeBackgroundTraitsForKeyplane:(id)arg1;
- (void)modifyKeyTraitsForPasscode:(id)arg1 forKey:(id)arg2 onKeyplane:(id)arg3;
@end

