//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardImpl.h>

@interface UIKeyboardImpl (UIKitInternal)
- (void)finishSplitTransitionWithProgress:(float)arg1;
- (void)setSplit:(BOOL)arg1 animated:(BOOL)arg2;
- (id)selectionView;
- (void)setInitialDirection;
- (BOOL)_shouldMinimizeForHardwareKeyboard;
- (void)setLongPress:(BOOL)arg1;
- (BOOL)keyboardDrawsOpaque;
- (void)clearEmojiLayout;
@end

