//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardEmojiCategoriesControl.h>

@class UIImage;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiCategoriesControl_iPad : UIKeyboardEmojiCategoriesControl
{
    UIImage *categoryKeyImage;
    UIImage *categoryKeyHighlightedImage;
    UIImage *dividerImage;
    UIImage *dividerHighlightedImage;
}

@property(retain) UIImage *dividerHighlightedImage; // @synthesize dividerHighlightedImage;
@property(retain) UIImage *dividerImage; // @synthesize dividerImage;
@property(retain) UIImage *categoryKeyHighlightedImage; // @synthesize categoryKeyHighlightedImage;
@property(retain) UIImage *categoryKeyImage; // @synthesize categoryKeyImage;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)frameForSegment:(int)arg1;
- (struct CGRect)frameForDivider:(int)arg1;
- (void)layoutSubviews;
- (void)releaseImagesAndViews;
- (void)updateSegmentAndDividers:(int)arg1;
- (void)updateSegmentImages;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

