//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardCandidateView.h>

#import "UIScrollViewDelegate.h"

@class UIKeyboardCandidatePageControl;

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateView_iPad : UIKeyboardCandidateView <UIScrollViewDelegate>
{
    UIKeyboardCandidatePageControl *_pageControl;
}

+ (float)defaultExtendedControlHeight;
- (void)didEndSplitTransition;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updatePageControlStatus;
- (float)_additionalClipHeight;
- (void)setCandidateBarExtended:(BOOL)arg1;
- (void)layoutSubviews;
- (unsigned int)_numberOfColumns:(BOOL)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

