//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardLayoutStar.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface UIKeyboardLayoutCursor : UIKeyboardLayoutStar
{
    UIView *_selectionView;
    long long _selectedKeyIndex;
}

- (void)physicalKeyDownWithEvent:(id)arg1;
- (void)remoteControlReceivedWithEvent:(id)arg1;
- (void)handleDirectionalInput:(int)arg1;
- (void)takeKeyAction:(id)arg1;
- (void)setSelectionPoint:(struct CGPoint)arg1;
- (void)setSelectedKeyIndex:(long long)arg1;
- (struct CGRect)selectionFrameForKeyIndex:(long long)arg1;
- (void)updateSelectionForCurrentKeyplane;
- (id)keyplaneKeyForCurrentKeyplane;
- (_Bool)acceptsDirectionInput;
- (void)setKeyboardAppearance:(long long)arg1;
- (void)showKeyboardWithInputTraits:(id)arg1 screenTraits:(id)arg2 splitTraits:(id)arg3;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

