//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol UIKeyboardSplitTransitionDelegate
- (void)transitionDidFinish;
- (void)updateFrame:(struct CGRect)arg1 withDuration:(float)arg2 splitHeightDelta:(float)arg3;
- (void)updateFrame:(struct CGRect)arg1 withDuration:(float)arg2;
@end

