//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardImpl.h>

@interface UIKeyboardImpl (TestingSupport)
- (_Bool)_needsCandidates;
- (void)_setNeedsCandidates:(_Bool)arg1;
- (long long)_positionInCandidateList:(id)arg1;
- (_Bool)_hasCandidates;
- (id)_getAutocorrection;
- (void)_setAutocorrects:(_Bool)arg1;
- (id)_getLocalizedInputMode;
- (id)_getCurrentKeyboardName;
- (id)_getCurrentKeyplaneName;
@end

