//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@protocol UIKeyboardLayoutProtocol <NSObject>
- (void)phraseBoundaryDidChange;
- (BOOL)shouldShowIndicator;
- (UIView *)activationIndicatorView;
- (void)clearAllKeyDelegates;
- (BOOL)updateKeysWithDelegates;
- (void)setDelegate:(id <UIKeyboardKeyDelegate>)arg1 forKey:(NSString *)arg2;
- (void)restoreDefaultsForAllKeys;
- (void)restoreDefaultsForKey:(id)arg1;
- (void)setLongPressAction:(SEL)arg1 forKey:(id)arg2;
- (void)setAction:(SEL)arg1 forKey:(id)arg2;
- (void)setTarget:(id)arg1 forKey:(id)arg2;
- (void)setLabel:(id)arg1 forKey:(id)arg2;
- (BOOL)hasCandidateKeys;
- (id <UIKeyboardCandidateList>)candidateList;
- (BOOL)performSpaceAction;
- (BOOL)performReturnAction;
- (void)didClearInput;
- (void)longPressAction;
- (BOOL)isShiftKeyBeingHeld;
- (void)setAutoshift:(BOOL)arg1;
- (void)setShift:(BOOL)arg1;
- (BOOL)ignoresShiftState;
- (BOOL)usesAutoShift;
- (void)updateLocalizedKeys:(BOOL)arg1;
- (void)deactivateActiveKeys;
- (void)clearUnusedObjects:(BOOL)arg1;
- (void)showKeyboardType:(int)arg1 withAppearance:(int)arg2;

@optional
- (void)setReturnKeyEnabled:(BOOL)arg1 withDisplayName:(NSString *)arg2 withType:(int)arg3;
- (void)deactivateActiveKeysClearingTouchInfo:(BOOL)arg1 clearingDimming:(BOOL)arg2;
- (void)deactivateActiveKeysClearingTouchInfo:(BOOL)arg1;
@end

