//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardLayoutEmoji.h>

__attribute__((visibility("hidden")))
@interface UIKeyboardLayoutEmoji_iPhone : UIKeyboardLayoutEmoji
{
}

- (struct CGRect)categoryFrame;
- (struct CGSize)rightControlSize;
- (struct CGSize)leftControlSize;
- (void)layoutSubviews;
- (void)updateControlButtonImages;
- (id)initWithFrame:(struct CGRect)arg1;

@end

