//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardImpl.h>

@interface UIKeyboardImpl (UIKeyboardLayoutLanguageAdapter)
- (void)callLayoutUpdateAllLocalizedKeys;
- (void)callLayoutUpdateLocalizedKeys;
- (void)callLayoutLongPressAction;
- (void)callLayoutSetAutoshift:(_Bool)arg1;
- (void)callLayoutSetShift:(_Bool)arg1;
- (_Bool)callLayoutIsShiftKeyBeingHeld;
- (_Bool)callLayoutIsShiftKeyPlaneChooser;
- (_Bool)callLayoutIgnoresShiftState;
- (_Bool)callLayoutUsesAutoShift;
- (void)callLayoutUpdateReturnKey;
@end

