//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardImpl.h>

@interface UIKeyboardImpl (UIKeyboardUnitTestSupport)
+ (void)_clearHardwareKeyboardMinimizationPreference;
- (void)logHandwritingData;
- (_Bool)isAutoDeleteActive;
- (void)testAutocorrectionPromptWithCorrection:(id)arg1;
- (int)textInputChangingCount;
- (_Bool)_isShowingCandidateUIWithAvailableCandidates;
- (void)updateFromTextInputTraits;
- (_Bool)hasAutoRepeat;
- (void)_setShiftLockedEnabled:(_Bool)arg1;
- (void)_setInputManager:(id)arg1;

// Remaining properties
@property(retain, nonatomic) id changedDelegate; // @dynamic changedDelegate;
@end

