//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiRecentsController : NSObject
{
    id <UIKeyboardEmojiController> _controller;
    int _currentSequence;
    NSMutableArray *_recents;
    NSMutableDictionary *_usageHistory;
}

- (id)recents;
- (id)defaultsDictionary;
- (void)clearAncientHistory;
- (void)emojiUsed:(id)arg1;
- (double)scoreForEmoji:(id)arg1;
- (double)scoreForSequence:(int)arg1;
- (BOOL)isAncientSequence:(int)arg1;
- (void)readDefaultsDictionary:(id)arg1;
- (void)dealloc;
- (id)initWithController:(id)arg1;

@end

