//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSMutableArray, UIImage;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiCategoriesControl : UIControl
{
    int _selected;
    int _total;
    UIImage *_darkDivider;
    UIImage *_plainDivider;
    UIImage *_selectedDivider;
    NSMutableArray *_segmentViews;
    NSMutableArray *_dividerViews;
}

+ (id)categoryControl;
@property int selectedIndex; // @dynamic selectedIndex;
@property(readonly) int numSegments; // @dynamic numSegments;
- (void)setFrame:(struct CGRect)arg1;
- (void)releaseImagesAndViews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

