//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, UIKeyboardCandidate, UIKeyboardLayout;

@protocol UIKeyboardCandidateList <NSObject>
- (void)configureKeyboard:(UIKeyboardLayout *)arg1;
- (unsigned int)count;
- (void)candidateAcceptedAtIndex:(unsigned int)arg1;
- (UIKeyboardCandidate *)candidateAtIndex:(unsigned int)arg1;
- (unsigned int)currentIndex;
- (UIKeyboardCandidate *)currentCandidate;
- (void)showPreviousPage;
- (void)showNextPage;
- (void)showPageAtIndex:(unsigned int)arg1;
- (void)showPreviousCandidate;
- (void)showNextCandidate;
- (void)showCandidate:(UIKeyboardCandidate *)arg1;
- (void)showCandidateAtIndex:(unsigned int)arg1;
- (void)setUIKeyboardCandidateListDelegate:(id <UIKeyboardCandidateListDelegate>)arg1;
- (void)layout;
- (void)setCandidates:(NSArray *)arg1 inlineText:(NSString *)arg2 inlineRect:(struct CGRect)arg3 maxX:(float)arg4 layout:(BOOL)arg5;

@optional
- (void)candidatesDidChange;
- (BOOL)hasPreviousPage;
- (BOOL)hasNextPage;
- (BOOL)handleTabKeyWithShift:(BOOL)arg1;
- (BOOL)handleNumberKey:(unsigned int)arg1;
- (void)setCompletionContext:(NSString *)arg1;
- (void)showCaret:(BOOL)arg1 gradually:(BOOL)arg2;
- (void)setInlineText:(NSString *)arg1;
- (void)setCandidates:(NSArray *)arg1 type:(int)arg2 inlineText:(NSString *)arg3 inlineRect:(struct CGRect)arg4 maxX:(float)arg5 layout:(BOOL)arg6;
@end

