//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIKBCacheableView.h"

@class NSString, UIKeyboardCandidate;

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateBarCell : UIView <UIKBCacheableView>
{
    UIKeyboardCandidate *m_candidate;
    NSString *m_candidateText;
    id m_target;
    SEL m_action;
    struct CGSize m_textSize;
    BOOL m_highlighted;
    BOOL m_special;
}

+ (id)fontForCandidateText:(id)arg1;
@property(readonly, nonatomic) struct CGSize stringSize; // @synthesize stringSize=m_textSize;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) float cachedWidth;
@property(readonly, nonatomic) BOOL cacheDeferable;
- (void)displayLayer:(id)arg1;
- (BOOL)shouldCache;
- (id)cacheKey;
@property(nonatomic) BOOL highlighted;
- (void)dealloc;
- (id)initWithCandidate:(id)arg1 tag:(int)arg2 target:(id)arg3 action:(SEL)arg4;
- (id)initWithCandidateText:(id)arg1 tag:(int)arg2 target:(id)arg3 action:(SEL)arg4;

@end

