//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (UILabelDeprecatedMethods)
- (struct CGSize)rawSize;
- (void)setRawSize:(struct CGSize)arg1;
- (void)drawContentsInRect:(struct CGRect)arg1;
- (struct CGRect)textRectForBounds:(struct CGRect)arg1;
- (struct CGSize)textSizeForWidth:(double)arg1;
- (_Bool)centersHorizontally;
- (void)setCentersHorizontally:(_Bool)arg1;
- (id)color;
- (void)setColor:(id)arg1;
- (void)_setColor:(id)arg1;
- (_Bool)autotrackTextToFit;
- (void)setAutotrackTextToFit:(_Bool)arg1;
@end

