//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (_UIAccessibilityButtonShapesSupportPrivate)
@property(nonatomic, setter=_setWantsUnderlineForAccessibilityButtonShapesEnabled:) _Bool _wantsUnderlineForAccessibilityButtonShapesEnabled; // @dynamic _wantsUnderlineForAccessibilityButtonShapesEnabled;
@end

