//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UILocalizedIndexedCollation.h>

@interface UILocalizedIndexedCollation (UIKitInternal)
+ (id)collationWithDictionary:(id)arg1;
- (struct __CFStringTokenizer *)tokenizer;
- (id)transformedCollationStringForString:(id)arg1;
- (id)initWithDictionary:(id)arg1;
@end

