//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, UIImageView;

__attribute__((visibility("hidden")))
@interface UIMovieScrubberEditingView : UIView
{
    UIImageView *_leftImageView;
    UIImageView *_middleImageView;
    UIImageView *_rightImageView;
    NSArray *_activeImages;
    NSArray *_inactiveImages;
    unsigned int _isActive:1;
    unsigned int _centerHandleEnabled:1;
}

- (float)_bounceValueForFraction:(float)arg1;
- (void)bounce;
@property(nonatomic, getter=isEditing) BOOL editing;
- (struct CGRect)rightHandleFrame;
- (struct CGRect)rightHandleBounds;
- (struct CGRect)leftHandleFrame;
- (struct CGRect)leftHandleBounds;
- (int)handleForPoint:(struct CGPoint)arg1 hitOffset:(float *)arg2;
- (BOOL)pointInsideCenterHandle:(struct CGPoint)arg1;
- (BOOL)pointInsideRightHandle:(struct CGPoint)arg1;
- (BOOL)pointInsideLeftHandle:(struct CGPoint)arg1;
- (void)setCenterHandleEnabled:(BOOL)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

