//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIInputViewAnimationStyle.h>

@class UINavigationControllerKeyboardAnimationStyleInfo, _UIViewControllerTransitionContext;

__attribute__((visibility("hidden")))
@interface UINavigationControllerKeyboardAnimationStyle : UIInputViewAnimationStyle
{
    _Bool _disableAlongsideView;
    _UIViewControllerTransitionContext *_context;
    UINavigationControllerKeyboardAnimationStyleInfo *_info;
}

+ (id)animationStyleWithoutAlongsideViewAnimated:(_Bool)arg1 duration:(double)arg2 outDirection:(int)arg3 context:(id)arg4;
+ (id)animationStyleAnimated:(_Bool)arg1 duration:(double)arg2 outDirection:(int)arg3 context:(id)arg4;
@property(readonly, nonatomic) UINavigationControllerKeyboardAnimationStyleInfo *info; // @synthesize info=_info;
@property(nonatomic) _Bool disableAlongsideView; // @synthesize disableAlongsideView=_disableAlongsideView;
@property(readonly, nonatomic) _UIViewControllerTransitionContext *context; // @synthesize context=_context;
- (void)launchAnimation:(CDUnknownBlockType)arg1 afterStarted:(CDUnknownBlockType)arg2 completion:(CDUnknownBlockType)arg3 forHost:(id)arg4 fromCurrentPosition:(_Bool)arg5;
- (void)dealloc;
- (id)initWithContext:(id)arg1;
- (_Bool)useCustomTransition;
- (_Bool)isAnimationCompleted;

@end

