//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface UINavigationController (_UIPalette)
- (void)_startPaletteTransitionIfNecessary:(id)arg1 animated:(_Bool)arg2;
- (void)detachPalette:(id)arg1;
- (void)detachPalette:(id)arg1 isInPaletteTransition:(_Bool)arg2;
- (id)existingPaletteForEdge:(unsigned long long)arg1;
- (void)_detachPalette:(id)arg1;
- (void)attachPalette:(id)arg1 isPinned:(_Bool)arg2;
- (id)paletteForEdge:(unsigned long long)arg1 size:(struct CGSize)arg2;
- (id)_pinningBarForPalette:(id)arg1;
- (struct CGRect)_boundsForPalette:(id)arg1 size:(struct CGSize)arg2;
- (struct CGRect)_frameForPalette:(id)arg1;
- (id)_topPalette;
@end

