//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIPasteboard.h>

@interface UIPasteboard (Static)
+ (id)_printPasteboard;
+ (id)_findPasteboard;
- (void)_pasteboardChanged:(id)arg1;
- (id)_initWithName:(id)arg1 system:(BOOL)arg2 create:(BOOL)arg3;
@end

