//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIThreePartButton.h>

@interface UIPlacardButton : UIThreePartButton
{
}

+ (id)defaultFont;
- (id)initWithTitle:(id)arg1 autosizesToFit:(BOOL)arg2 isShort:(BOOL)arg3;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 isShort:(BOOL)arg2;

@end

