//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIPreferencesTableCell.h>

@class UIControl;

@interface UIPreferencesControlTableCell : UIPreferencesTableCell
{
    UIControl *_control;
}

- (void)setUserInteractionEnabled:(BOOL)arg1;
- (void)_controlClicked:(id)arg1;
- (id)control;
- (void)setControl:(id)arg1;

@end

