//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIPrintInteractionController.h>

@interface UIPrintInteractionController (UIPrintInteractionController_Private)
- (void)_cancelManualPrintPage;
- (void)_manualPrintPage;
- (void)_enableManualPrintPage:(_Bool)arg1;
@end

