//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIPushButton.h>

@interface UIPushButton (Original)
- (void)setShadowColor:(id)arg1;
- (id)titleColor;
- (void)setHighlightedTitleColor:(id)arg1;
- (void)setTitleColor:(id)arg1;
- (id)image;
- (void)setPressedImage:(id)arg1;
- (void)setImage:(id)arg1;
@end

