//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIPushButton.h>

@interface UIPushButton (Static)
- (void)_setNeedsDisplay:(CDStruct_89ddc8e1)arg1;
- (CDStruct_89ddc8e1)_currentButtonStateInfo;
- (void)_removePressFeedback:(id)arg1 finished:(id)arg2;
@end

