//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "UITextInputAdditions.h"

@interface UIResponder (UITextInputAdditions) <UITextInputAdditions>
- (void)endSelectionChange;
- (void)beginSelectionChange;
@property(readonly, nonatomic, getter=_caretRect) struct CGRect caretRect;
- (id)_asTextSelection;
@property(readonly, nonatomic, getter=isEditing) _Bool editing;
@property(readonly, nonatomic, getter=isEditable) _Bool editable;
- (id)interactionAssistant;
- (id)textInputView;
@end

