//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

__attribute__((visibility("hidden")))
@interface UIScrollerIndicator : UIView
{
    int _style;
}

- (void)drawRect:(struct CGRect)arg1;
- (id)initInScroller:(id)arg1 style:(int)arg2;

@end

