//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UIScreenMode : NSObject
{
    id _mode;
}

+ (id)screenModeForDisplayMode:(id)arg1;
- (id)description;
- (id)_displayMode;
- (BOOL)_isNTSCOrPAL;
@property(readonly, nonatomic) float pixelAspectRatio;
@property(readonly, nonatomic) struct CGSize size;
- (id)initWithDisplayMode:(id)arg1;

@end

