//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface UISharedImageStatistics : NSObject
{
    double _loadTime;
    double _requestTime;
    unsigned int _requests;
    unsigned int _flushes;
}

@property(nonatomic) unsigned int flushes; // @synthesize flushes=_flushes;
@property(nonatomic) unsigned int requests; // @synthesize requests=_requests;
@property(nonatomic) double requestTime; // @synthesize requestTime=_requestTime;
@property(nonatomic) double loadTime; // @synthesize loadTime=_loadTime;

@end

