//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UISharedArtwork.h>

@interface UISharedArtwork (Introspection)
- (void)enumerateImageInfoWithBlock:(CDUnknownBlockType)arg1;
- (id)imageNamed:(id)arg1 scale:(int)arg2 device:(int)arg3;
@end

