//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UIStatusBarAnimationParameters : NSObject
{
    double _startTime;
    double _duration;
    int _curve;
}

@property(nonatomic) int curve; // @synthesize curve=_curve;
@property(nonatomic) double duration; // @synthesize duration=_duration;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
- (id)initWithEmptyParameters;
- (id)initWithDefaultParameters;
- (id)init;

@end

