//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIStatusBarLegacyStyleAttributes.h>

__attribute__((visibility("hidden")))
@interface UIStatusBarLegacyBlackOpaqueStyleAttributes : UIStatusBarLegacyStyleAttributes
{
    _Bool _hasCorners;
}

- (id)backgroundImageName;
- (int)cornerStyle;
- (id)initWithRequest:(id)arg1;
- (id)initWithRequest:(id)arg1 hasCorners:(_Bool)arg2;

@end

