//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIStatusBarAnimationParameters.h>

@interface UIStatusBarStyleAnimationParameters : UIStatusBarAnimationParameters
{
    int _styleAnimation;
    double _delay;
}

@property(nonatomic) double delay; // @synthesize delay=_delay;
@property(nonatomic) int styleAnimation; // @synthesize styleAnimation=_styleAnimation;
- (id)initWithDefaultParameters;

@end

