//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

@class UIImage;

@interface UITableHeaderFooterView : UITableViewHeaderFooterView
{
    UIImage *_backgroundImage;
    int _tableViewStyle;
}

- (void)setBackgroundImage:(id)arg1;
- (id)backgroundImage;
- (void)setText:(id)arg1;
- (void)setTableViewStyle:(int)arg1;

@end

