//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIControl.h>

__attribute__((visibility("hidden")))
@interface UITableViewCellDeleteConfirmationControl : UIControl
{
    BOOL _visible;
}

+ (struct CGSize)defaultSizeForTitle:(id)arg1;
- (void)removeFromSuperview;
- (void)layoutSubviews;
@property(nonatomic, getter=isVisible) BOOL visible;
- (void)setVisible:(BOOL)arg1 animated:(BOOL)arg2;
- (void)cancelTrackingWithEvent:(id)arg1;
- (void)endTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (BOOL)continueTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (BOOL)beginTrackingWithTouch:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (struct CGSize)defaultSize;
- (id)initWithTitle:(id)arg1;

@end

