//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewRowData.h>

@interface UITableViewRowData (UITableViewRowDataPrivate)
- (int)_sectionRowForGlobalRow:(int)arg1 inSection:(int *)arg2;
- (void)_ensureSectionOffsetIsValidForSection:(int)arg1;
- (void)_updateSectionRowDataArrayForNumSections:(int)arg1;
- (void)_updateNumSections;
@end

