//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewCellDeleteConfirmationControl.h>

@interface UITableViewCellDeleteConfirmationControl (UITableViewCellDeleteConfirmationControlStatic)
- (id)_interceptEvent:(id)arg1;
- (id)_interceptMouseEvent:(struct __GSEvent *)arg1;
- (void)_setInterceptMouseEvent:(BOOL)arg1;
- (void)_confirmationAnimationDidEnd;
@end

