//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewCellEditControl.h>

@interface UITableViewCellEditControl (UITableViewCellEditControlStatic)
+ (id)_multiSelectHighlightedImage;
+ (id)_multiSelectSelectedImage;
+ (id)_multiSelectNotSelectedImage;
+ (id)_insertImage:(double)arg1;
+ (id)_deleteImage:(double)arg1;
+ (id)_deleteImageBackground:(double)arg1;
+ (struct CGRect)_minusRect;
- (id)_currentImage;
- (void)_toggleRotate;
- (void)_updateImageView;
- (id)_minusView;
@end

