//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITabBarItem.h>

@interface UITabBarItem (Static)
+ (id)_appearanceBlindViewClasses;
- (void)_updateView;
- (void)_updateViewAndPositionItems:(_Bool)arg1;
- (id)_createViewForTabBar:(id)arg1 showingBadge:(_Bool)arg2 withTint:(_Bool)arg3;
- (id)_createViewForTabBar:(id)arg1 showingBadge:(_Bool)arg2;
- (void)_setTitleTextAttributeValue:(id)arg1 forAttributeKey:(id)arg2 state:(unsigned long long)arg3;
- (id)nextResponder;
- (id)_updateImageWithTintColor:(id)arg1 isSelected:(_Bool)arg2 getImageOffset:(struct UIOffset *)arg3;
- (void)_updateButtonForTintColor:(id)arg1 selected:(_Bool)arg2;
@end

