//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITextInput.h"
#import "UITextInputTokenizer.h"
#import "UITextInputTraits_Private.h"

@class DOMRange, NSArray, NSString, UIColor, UIFont, UITextInputTraits, UITextInteractionAssistant, UITextPosition, UITextRange, UIView, WebEvent;

@protocol UITextInputPrivate <UITextInput, UITextInputTokenizer, UITextInputTraits_Private>
@property(readonly, nonatomic) UITextInteractionAssistant *interactionAssistant;
- (BOOL)hasSelection;
- (UIFont *)fontForCaretSelection;
- (UIColor *)textColorForCaretSelection;
- (void)selectAll;
- (BOOL)hasContent;
- (void)setMarkedText:(NSString *)arg1;
- (NSString *)markedText;
- (DOMRange *)wordRangeContainingCaretSelection;
- (NSString *)wordContainingCaretSelection;
- (unsigned short)characterBeforeCaretSelection;
- (void)moveForward:(unsigned int)arg1;
- (void)moveBackward:(unsigned int)arg1;
- (struct CGRect)rectContainingCaretSelection;
- (void)replaceRangeWithTextWithoutClosingTyping:(UITextRange *)arg1 replacementText:(NSString *)arg2;
- (void)setSelectedDOMRange:(DOMRange *)arg1 affinityDownstream:(BOOL)arg2;
- (DOMRange *)selectedDOMRange;
- (struct _NSRange)_markedTextNSRange;
- (struct CGRect)rectForNSRange:(struct _NSRange)arg1;
- (struct _NSRange)selectionRange;
- (UITextInputTraits *)textInputTraits;

@optional
@property(nonatomic) int selectionGranularity;
- (UITextPosition *)nextUnperturbedDictationResultBoundaryFromPosition:(UITextPosition *)arg1;
- (UITextPosition *)previousUnperturbedDictationResultBoundaryFromPosition:(UITextPosition *)arg1;
- (NSArray *)metadataDictionariesForDictationResults;
- (void)insertDictationResult:(NSArray *)arg1 withCorrectionIdentifier:(id)arg2;
- (UIView *)automaticallySelectedOverlay;
- (void)setBottomBufferHeight:(float)arg1;
- (void)handleKeyWebEvent:(WebEvent *)arg1;
- (BOOL)requiresKeyEvents;
@end

