//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITextEffectsWindow.h>

#import "_UIScreenBasedObject.h"

@class UIScreen;

@interface UITextEffectsWindow (UIObjectsForPerScreen) <_UIScreenBasedObject>
@property(readonly) UIScreen *_intendedScreen;
- (_Bool)_matchingOptions:(id)arg1;
- (id)_initWithScreen:(id)arg1 options:(id)arg2;
@end

