//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UITextRange;

__attribute__((visibility("hidden")))
@interface UITextSelectionRect : NSObject
{
}

+ (struct CGRect)endEdgeFromRects:(id)arg1;
+ (struct CGRect)startEdgeFromRects:(id)arg1;
@property(readonly, nonatomic) UITextRange *range;
@property(readonly, nonatomic) int writingDirection;
@property(readonly, nonatomic) struct CGRect rect;

@end

