//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITextRange.h>

@class UITextRangeImpl;

@interface UITextRange (UITextInputAdditions)
@property(readonly, nonatomic, getter=_isImpl) UITextRangeImpl *isImpl;
@property(readonly, nonatomic, getter=_isRanged) _Bool isRanged;
@property(readonly, nonatomic, getter=_isCaret) _Bool isCaret;
@end

