//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIResponder<UITextInput>, UIView;

@protocol UITextMagnifier <NSObject>
@property(nonatomic) struct CGPoint animationPoint;
@property(nonatomic) struct CGPoint magnificationPoint;
@property(readonly, nonatomic) BOOL terminalPointPlacedCarefully;
@property(readonly, nonatomic) struct CGPoint terminalPoint;
@property(readonly, nonatomic) UIView *target;
- (void)autoscrollWillNotStart;
- (void)setAutoscrollDirections:(int)arg1;
- (void)postAutoscrollPoint:(struct CGPoint)arg1;
- (void)stopMagnifying:(BOOL)arg1;
- (void)beginMagnifyingTarget:(UIView *)arg1 text:(UIResponder<UITextInput> *)arg2 magnificationPoint:(struct CGPoint)arg3 offset:(struct CGPoint)arg4 animated:(BOOL)arg5;
@end

