//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIToolbar.h>

@interface UIToolbar (SynthEvents)
- (id)scriptingInfoWithChildren;
- (void)_updateScriptingInfo:(id)arg1 view:(id)arg2;
- (id)_buttonName:(id)arg1 withType:(int)arg2;
@end

