//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIToolbar.h>

@interface UIToolbar (UIButtonBarInternal)
+ (float)_buttonGap;
- (BOOL)_isTopBar;
- (BOOL)_isInNavigationBar;
- (id)_customToolbarAppearance;
- (void)_positionToolbarButtons:(id)arg1 ignoringItem:(id)arg2;
- (id)_positionToolbarButtons:(id)arg1 ignoringItem:(id)arg2 actuallyRepositionButtons:(BOOL)arg3;
- (void)_alertWillShow:(BOOL)arg1 duration:(float)arg2;
- (BOOL)_isPositionedHiddenForAlert;
- (void)_updateBackgroundImage;
- (id)_currentCustomBackgroundRespectOversize:(char *)arg1;
@end

