//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIAlertView.h>

@class NSUndoManager;

__attribute__((visibility("hidden")))
@interface UIUndoAlertView : UIAlertView
{
    int _undoButtonIndex;
    int _redoButtonIndex;
    NSUndoManager *_undoManager;
}

@property(readonly, nonatomic) NSUndoManager *undoManager; // @synthesize undoManager=_undoManager;
@property(readonly, nonatomic) int redoButtonIndex; // @synthesize redoButtonIndex=_redoButtonIndex;
@property(readonly, nonatomic) int undoButtonIndex; // @synthesize undoButtonIndex=_undoButtonIndex;
- (void)dealloc;
- (void)show;
- (id)initWithDelegate:(id)arg1 undoManager:(id)arg2;

@end

