//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface UIURLResolver : NSObject
{
}

+ (void)invalidate;
+ (id)sharedResolver;
+ (id)urlCacheChangedNotificationName;
+ (id)urlCacheName;
- (BOOL)_url:(id)arg1 matchesHostWhitelist:(id)arg2;
- (BOOL)_url:(id)arg1 matchesHostPatterns:(id)arg2 pathPatterns:(id)arg3;
- (BOOL)_string:(id)arg1 matchesPatterns:(id)arg2;
- (void)dealloc;
- (id)init;
- (id)initWithDictionary:(id)arg1;

@end

