//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (ViewServices)
+ (id)_exportedInterface;
+ (id)_remoteViewControllerInterface;
- (CDStruct_4c969caf)_hostAuditToken;
- (int)_hostProcessIdentifier;
- (id)_remoteViewControllerProxyWithErrorHandler:(CDUnknownBlockType)arg1;
- (id)_remoteViewControllerProxy;
- (id)_hostApplicationBundleIdentifier;
- (void)_supportedInterfaceOrientationsDidChange;
- (void)_hostApplicationDidEnterBackground;
- (void)_hostApplicationWillEnterForeground;
- (void)_willAppearInRemoteViewController:(id)arg1;
- (void)_willAppearInRemoteViewController;
@end

