//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray;

@interface UIViewController (UIContainerViewControllerProtectedMethods)
- (void)transitionFromViewController:(id)arg1 toViewController:(id)arg2 duration:(double)arg3 options:(unsigned int)arg4 animations:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
- (void)removeFromParentViewController;
- (void)addChildViewController:(id)arg1;
@property(readonly, nonatomic) NSArray *childViewControllers;
@end

