//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (UIModalItemPresentationSupport)
- (void)dismissModalItem:(id)arg1 withTappedButtonIndex:(long long)arg2 animated:(_Bool)arg3;
- (void)updateModaltem:(id)arg1 animated:(_Bool)arg2;
- (void)presentModalItem:(id)arg1 animated:(_Bool)arg2;
- (void)presentModalItem:(id)arg1 animated:(_Bool)arg2 dontPresentAndAddToStack:(_Bool)arg3;
- (void)presentModalItem:(id)arg1 replacing:(id)arg2 animated:(_Bool)arg3;
- (void)presentModalItem:(id)arg1 replacing:(id)arg2 animated:(_Bool)arg3 dontPresentAndAddToStack:(_Bool)arg4;
@end

