//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (UITouchInternalCompatibility)
- (id)_syntheticUIEventWithGSEvent:(struct __GSEvent *)arg1 touchPhase:(long long)arg2;
- (id)_syntheticTouch;
@end

