//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class UITabBarController, UITabBarItem;

@interface UIViewController (UITabBarControllerItem)
- (id)moreListTableCell;
- (id)moreListSelectedImage;
- (id)moreListImage;
- (id)_moreListTitle;
- (void)updateTabBarItemForViewController:(id)arg1;
@property(readonly, nonatomic) UITabBarController *tabBarController;
@property(retain, nonatomic) UITabBarItem *tabBarItem;
@end

