//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (StateRestoration)
- (_Bool)_shouldLoadViewDuringRestoration:(id)arg1;
- (void)applicationFinishedRestoringState;
- (void)decodeRestorableStateWithCoder:(id)arg1;
- (void)_presentViewControllerForStateRestoration:(id)arg1;
- (void)encodeRestorableStateWithCoder:(id)arg1;
- (id)_allContainedViewControllers;
- (void)setStoryboardIdentifier:(id)arg1;
- (id)storyboardIdentifier;
- (void)setRestorationClass:(Class)arg1;
- (Class)restorationClass;
- (id)_restorationClassName;
@end

