//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (UIPrintFormatter)
- (void)drawRect:(struct CGRect)arg1 forViewPrintFormatter:(id)arg2;
- (id)viewPrintFormatter;
- (Class)_printFormatterClass;
@end

