//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@interface UIViewController (UINavigationControllerContextualToolbar)
- (void)_updateToolbarItemsFromViewController:(id)arg1 animated:(_Bool)arg2;
- (void)setToolbarItems:(id)arg1 animated:(_Bool)arg2;
- (void)setToolbarItems:(id)arg1;
- (id)toolbarItems;
@end

