//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (UIViewStyleAdditions)
+ (id)_tintColorForStyle:(int)arg1;
- (int)_style;
- (int)_containerStyle;
@end

