//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIKBRenderConfig;

@interface UIView (UIKB_UIViewExtras)
@property(readonly, nonatomic) _Bool _lightStyleRenderConfig;
@property(readonly, nonatomic) UIKBRenderConfig *_inheritedRenderConfig;
- (void)_setRenderConfig:(id)arg1;
- (int)_clipCornersOfView:(id)arg1;
- (int)_clipCorners;
- (void)resizeForKeyplaneSize:(struct CGSize)arg1;
@end

