//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIWebDocumentView.h>

@interface UIWebDocumentView (InteractionPrivate)
- (void)_showDataDetectorsSheet;
- (void)_showLinkSheet;
- (void)_showImageSheet;
- (void)_createSheetWithElementActions:(id)arg1 showLinkTitle:(BOOL)arg2;
@end

