//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIImageView;

__attribute__((visibility("hidden")))
@interface UIWebDragDotView : UIView
{
    UIColor *m_insertionPointColor;
    UIColor *m_selectionBarColor;
    UIImageView *m_dot;
    BOOL m_dotAtTop;
}

@property(nonatomic) BOOL showsBall;
- (void)drawRect:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 container:(id)arg2 withDotAtTop:(BOOL)arg3;

@end

