//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WebHTMLRepresentation.h"

@interface WebHTMLRepresentation (CreditCardAutoFillExtras)
- (BOOL)formElementLooksLikeSecurityCodeField:(id)arg1;
- (BOOL)formElementLooksLikeCreditCardNumberField:(id)arg1;
@end

