//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate.h"
#import "_UIAlertActionRepresenting.h"

@class NSLayoutConstraint, NSMutableArray, NSString, UIAlertAction, UIAlertControllerVisualStyle, UIImageView, UILabel, UITapGestureRecognizer, UIView<UIAlertControllerBackgroundView>;

__attribute__((visibility("hidden")))
@interface _UIAlertControllerActionView : UIView <UIGestureRecognizerDelegate, _UIAlertActionRepresenting>
{
    NSLayoutConstraint *_minimumHeightConstraint;
    UIView *labelContainerView;
    NSLayoutConstraint *_labelContainerLeadingConstraint;
    NSLayoutConstraint *_labelContainerTrailingConstraint;
    UILabel *label;
    UILabel *descriptiveLabel;
    UIImageView *imageView;
    UIImageView *checkView;
    UIView<UIAlertControllerBackgroundView> *highlightedBackgroundContainerView;
    NSMutableArray *highlightedBackgroundConstraints;
    NSMutableArray *havingDescriptiveLabelConstraints;
    NSMutableArray *notHavingDescriptiveLabelConstraints;
    NSLayoutConstraint *_descriptiveLabelWidthConstraint;
    NSMutableArray *_contentViewControllerConstraints;
    UIView *_contentViewControllerContainerView;
    UIAlertAction *_action;
    UIAlertControllerVisualStyle *_visualStyle;
    id selectedTarget;
    SEL selectedAction;
    id highlightTarget;
    SEL highlightAction;
    _Bool _hasDescriptiveText;
    UITapGestureRecognizer *_selectGestureRecognizer;
    _Bool _discrete;
    _Bool _highlighted;
}

@property(nonatomic, getter=isHighlighted) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property _Bool discrete; // @synthesize discrete=_discrete;
- (void)_action:(id)arg1 updatedTitleTextColor:(id)arg2;
- (void)_action:(id)arg1 updatedImageTintColor:(id)arg2;
- (void)_action:(id)arg1 changedToBeDefault:(_Bool)arg2;
- (void)_action:(id)arg1 changedToChecked:(_Bool)arg2;
- (void)_action:(id)arg1 changedToEnabled:(_Bool)arg2;
- (void)_action:(id)arg1 changedToTitleTextAlignment:(long long)arg2;
- (void)_action:(id)arg1 changedToTitle:(id)arg2;
- (void)focusedViewDidChange;
- (_Bool)canBecomeFocused;
- (long long)_physicalButtonTypeForBackGesture;
- (long long)_physicalButtonTypeForSelectGesture;
- (void)_selectGestureChanged:(id)arg1;
- (void)_uninstallSelectGestureRecognizer;
- (void)_installSelectGestureRecognizer;
- (void)traitCollectionDidChange:(id)arg1;
- (_Bool)_idiomSupportsSelectGesture:(long long)arg1;
- (id)_titleFont;
- (double)_minimumLabelScaleFactor;
- (void)_contentSizeChanged;
@property(readonly, copy) NSString *description;
- (id)_computedTintColor;
- (id)tintColor;
- (void)tintColorDidChange;
@property(copy, nonatomic) UIAlertAction *action;
- (void)_updateStyle;
@property UIAlertControllerVisualStyle *visualStyle;
- (void)_updateLabelContainerConstraints;
- (void)_updateTextAlignmentForDescriptiveText:(_Bool)arg1 titleTextAlignment:(long long)arg2;
- (void)_updateBackgroundView;
- (void)_updateMinimumHeight;
- (void)_updateFontSize;
- (void)_recomputeBackgroundColor;
- (void)_recomputeTextColor;
- (void)dealloc;
- (void)setHighlightTarget:(id)arg1 action:(SEL)arg2;
- (void)setSelectedTarget:(id)arg1 action:(SEL)arg2;
@property(readonly) double currentDescriptiveLabelTextWidth;
@property double alignedDescriptiveLabelTextWidth;
- (void)_triggerSelect;
- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
- (void)_physicalButtonsCancelled:(id)arg1 withEvent:(id)arg2;
- (void)_physicalButtonsEnded:(id)arg1 withEvent:(id)arg2;
- (void)_physicalButtonsBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)_buttonsShouldShowPressedState:(id)arg1;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)_touchForEvent:(id)arg1;
- (void)_prepareConstraintsForDescriptiveText:(_Bool)arg1;
- (void)_prepareConstraints;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

