//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

__attribute__((visibility("hidden")))
@interface _UIBackgroundTaskInfo : NSObject
{
    unsigned int _taskId;
    CDUnknownBlockType _expireHandler;
    struct SBSProcessAssertion *_processAssertion;
    int _count;
}

- (void)invalidate;
- (void)fireExpirationHandler;
- (void)dealloc;
- (id)initWithProcessAssertion:(struct SBSProcessAssertion *)arg1 expirationHandler:(CDUnknownBlockType)arg2;

@end

