//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSMutableArray, UIReferenceLibraryViewController, _UIDictionaryDownloadConfirmView, _UIDictionaryDownloadProgressView;

__attribute__((visibility("hidden")))
@interface _UIDictionaryDownloadViewController : UIViewController
{
    _UIDictionaryDownloadConfirmView *_downloadConfirmView;
    _UIDictionaryDownloadProgressView *_downloadProgressView;
    NSMutableArray *_assetsDownloadList;
    UIReferenceLibraryViewController *_referenceLibraryController;
}

@property(nonatomic) UIReferenceLibraryViewController *referenceLibraryController; // @synthesize referenceLibraryController=_referenceLibraryController;
- (void)userWantsToDownload:(id)arg1;
- (void)downloadAsset:(id)arg1;
- (void)addAssetForDownload:(id)arg1;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

