//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UILabel, UIProgressView;

__attribute__((visibility("hidden")))
@interface _UIDictionaryDownloadProgressView : UIView
{
    UIProgressView *_progressView;
    UILabel *_downloadProgressLabel;
    NSString *_downloadStatusText;
    float _downloadProgress;
}

- (void)layoutSubviews;
@property(copy, nonatomic) NSString *downloadStatusText; // @synthesize downloadStatusText=_downloadStatusText;
@property(nonatomic) float downloadProgress; // @synthesize downloadProgress=_downloadProgress;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

