//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, NSURL, UINavigationItem;

@protocol _UIDocumentPickerServiceViewController <NSObject>
@property(nonatomic) long long displayMode;
@property(nonatomic) int sortOrder;
@property(readonly, copy, nonatomic) NSURL *uploadURL;
@property(readonly, nonatomic) unsigned long long pickerMode;
@property(readonly, copy, nonatomic) NSArray *pickableTypes;
- (_Bool)shouldShowSearch;
- (void)dismissWithURL:(NSURL *)arg1 forBundleIdentifier:(NSString *)arg2;
- (void)setupNavigationItemForPicker:(UINavigationItem *)arg1 isRoot:(_Bool)arg2;
@end

