//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class NSArray, UIButton, UISegmentedControl;

__attribute__((visibility("hidden")))
@interface _UIDocumentPickerSortOrderView : UIControl
{
    id <_UIDocumentPickerViewServiceViewController> _serviceViewController;
    long long _listMode;
    UISegmentedControl *_sortOrder;
    UIButton *_listModeToggle;
    NSArray *_compactConstraints;
    NSArray *_regularConstraints;
}

@property(copy, nonatomic) NSArray *regularConstraints; // @synthesize regularConstraints=_regularConstraints;
@property(copy, nonatomic) NSArray *compactConstraints; // @synthesize compactConstraints=_compactConstraints;
@property(retain, nonatomic) UIButton *listModeToggle; // @synthesize listModeToggle=_listModeToggle;
@property(retain, nonatomic) UISegmentedControl *sortOrder; // @synthesize sortOrder=_sortOrder;
@property(nonatomic) long long listMode; // @synthesize listMode=_listMode;
@property(nonatomic) id <_UIDocumentPickerViewServiceViewController> serviceViewController; // @synthesize serviceViewController=_serviceViewController;
- (void)_toggleListMode:(id)arg1;
- (void)valueChanged:(id)arg1;
@property(nonatomic) int value;
- (void)dealloc;
- (void)updateForListMode;
- (void)traitCollectionDidChange:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

