//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "_UIDocumentPickerServiceInvalidating.h"

@class NSString, UIViewController<_UIDocumentPickerContainedViewController>, _UIDocumentPickerContainerModel, _UIDocumentPickerViewServiceViewController, _UINavigationControllerPalette;

__attribute__((visibility("hidden")))
@interface _UIDocumentPickerContainerViewController : UIViewController <_UIDocumentPickerServiceInvalidating>
{
    _UIDocumentPickerViewServiceViewController *_weak_serviceViewController;
    _Bool _rootContainer;
    _UIDocumentPickerContainerModel *_model;
    UIViewController<_UIDocumentPickerContainedViewController> *_childViewController;
    _UINavigationControllerPalette *_searchPalette;
}

@property(nonatomic, getter=isRootContainer) _Bool rootContainer; // @synthesize rootContainer=_rootContainer;
@property(retain, nonatomic) _UINavigationControllerPalette *searchPalette; // @synthesize searchPalette=_searchPalette;
@property(retain, nonatomic) UIViewController<_UIDocumentPickerContainedViewController> *childViewController; // @synthesize childViewController=_childViewController;
@property(retain, nonatomic) _UIDocumentPickerContainerModel *model; // @synthesize model=_model;
- (void)_tryExportingFile:(id)arg1 toLocation:(id)arg2;
- (id)_mangledFilenameForURL:(id)arg1;
- (void)_pickCurrentLocationForUpload:(id)arg1;
- (void)_updateForServiceView;
- (void)invalidate;
- (void)teardownPalettes;
- (void)setupPalettes;
- (void)didMoveToParentViewController:(id)arg1;
- (void)willMoveToParentViewController:(id)arg1;
@property(nonatomic) __weak id <_UIDocumentPickerServiceViewController> serviceViewController;
- (void)_sortOrderViewChanged:(id)arg1;
- (void)viewDidLayoutSubviews;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setChildViewController:(id)arg1 animated:(_Bool)arg2;
- (void)ensureChildViewController;
- (id)url;
- (void)dealloc;
- (id)initWithModel:(id)arg1;
- (id)initWithURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

