//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSSecureCoding.h"

@class NSMutableArray, UIView;

__attribute__((visibility("hidden")))
@interface _UIFocusRegionMap : NSObject <NSSecureCoding>
{
    _Bool _builtRegionMap;
    NSMutableArray *_mapEntries;
    UIView *_containingView;
    struct CGSize _windowSize;
}

+ (_Bool)supportsSecureCoding;
@property(retain, nonatomic) UIView *containingView; // @synthesize containingView=_containingView;
@property(retain, nonatomic) NSMutableArray *mapEntries; // @synthesize mapEntries=_mapEntries;
@property(nonatomic) struct CGSize windowSize; // @synthesize windowSize=_windowSize;
- (id)debugQuickLookObject;
- (id)debuggingImage;
- (void)_buildRegionMap;
- (id)linearlyOrderedFocusRegionMaps;
- (id)linearlyOrderedFocusViews;
- (id)closestFocusableViewFromRect:(struct CGRect)arg1 inDirection:(struct CGSize)arg2 includeCurrentlyFocused:(_Bool)arg3;
- (id)closestFocusableViewFromRect:(struct CGRect)arg1 inDirection:(struct CGSize)arg2;
- (void)_punchHoleInMapAtFrame:(struct CGRect)arg1;
- (void)addUnfocusableView:(id)arg1 withFrameInWindow:(struct CGRect)arg2;
- (void)addFocusableView:(id)arg1 withFrameInWindow:(struct CGRect)arg2;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithContainingView:(id)arg1;
- (id)init;

@end

