//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSMapTable, NSString, NSUserDefaults, UIMoveEvent, UIPanGestureRecognizer, UIScrollView, UIWindow, _UIDynamicAnimationGroup, _UIFocusEngineTapGestureRecognizer, _UIFocusEngineTargetedDynamicAnimation, _UIFocusTouchDebugView;

@interface _UIFocusEngine : NSObject <UIGestureRecognizerDelegate>
{
    UIPanGestureRecognizer *_panGestureRecognizer;
    _UIFocusEngineTapGestureRecognizer *_tapGestureRecognizer;
    struct CGPoint _movementOriginPoint;
    struct CGPoint _originalTouchPointNormalized;
    struct CGPoint _lastTouchPointNormalized;
    struct CGPoint _momentumNormalized;
    _UIDynamicAnimationGroup *_touchMomentumAnimationGroup;
    _UIFocusEngineTargetedDynamicAnimation *_scrollAnimationAxisX;
    _UIFocusEngineTargetedDynamicAnimation *_scrollAnimationAxisY;
    _UIDynamicAnimationGroup *_scrollAnimationGroup;
    NSArray *_remoteGestures;
    _UIFocusEngineTargetedDynamicAnimation *_focusDirectionRollbackAnimation;
    unsigned long long _currentGestureID;
    unsigned int _tickSoundID;
    UIScrollView *_lastScrolledScroll;
    double _lastEdgeScrollEdgeValue;
    NSUserDefaults *_userDefaults;
    _UIFocusTouchDebugView *_touchIndicatorView;
    NSMapTable *_activeScrollViewBounds;
    struct {
        unsigned int isSettingFocusedView:1;
        unsigned int isTrackingTouch:1;
        unsigned int isContinuingTouchWithMomentum:1;
        unsigned int isAnimatingFocusDirectionRollback:1;
        unsigned int shouldShowDebugOverlays:1;
    } _flags;
    _Bool _enabled;
    _Bool _shouldShowDebugOverlays;
    _Bool _sendsFocusDirection;
    _Bool _playsSoundOnFocusChange;
    UIWindow *_targetWindow;
    UIMoveEvent *_moveEvent;
}

+ (void)initialize;
+ (void)resetTuningValuesIfNecessary;
+ (void)resetTuningValues;
+ (id)defaultTuningValues;
@property(nonatomic, getter=_playsSoundOnFocusChange, setter=_setPlaysSoundOnFocusChange:) _Bool playsSoundOnFocusChange; // @synthesize playsSoundOnFocusChange=_playsSoundOnFocusChange;
@property(nonatomic, getter=_sendsFocusDirection, setter=_setSendsFocusDirection:) _Bool sendsFocusDirection; // @synthesize sendsFocusDirection=_sendsFocusDirection;
@property(retain, nonatomic) UIMoveEvent *moveEvent; // @synthesize moveEvent=_moveEvent;
@property(nonatomic) _Bool shouldShowDebugOverlays; // @synthesize shouldShowDebugOverlays=_shouldShowDebugOverlays;
@property(nonatomic) UIWindow *targetWindow; // @synthesize targetWindow=_targetWindow;
@property(nonatomic, getter=isEnabled) _Bool enabled; // @synthesize enabled=_enabled;
- (id)_closestFocusableViewToPoint:(struct CGPoint)arg1 inView:(id)arg2;
- (id)_closestFocusableViewToRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)_updateDebugOverlayByRemovingTouchIndicators;
- (void)_updateDebugOverlayWithTouchAtNormalizedPoint:(struct CGPoint)arg1 navigationBoundary:(struct CGRect)arg2;
- (void)_teardownDebugOverlays;
- (void)_setupDebugOverlays;
- (void)_sendGestureEndNotification;
- (void)_sendGestureBeginNotification;
- (struct CGRect)_visibleBoundsForScrollView:(id)arg1;
- (struct CGPoint)_contentOffsetForScrollView:(id)arg1 toFocusView:(id)arg2;
- (void)_scrollFromView:(id)arg1 toView:(id)arg2;
- (void)_continueTouchWithMomentum;
- (void)_recordMomentumForPoint:(struct CGPoint)arg1;
- (void)_resetMomentum;
- (void)_startFocusDirectionRollback;
- (void)_panGestureEnd:(id)arg1;
- (void)_panGestureUpdate:(id)arg1 atLocation:(struct CGPoint)arg2 reportedVelocity:(struct CGPoint)arg3;
- (void)_panGestureStart:(id)arg1;
- (void)_resetFocusDirectionRollback;
- (void)_updateFocusedViewAndScroll:(id)arg1;
- (_Bool)_moveFocusAlongVector:(struct CGSize)arg1;
- (struct CGSize)_touchSensitivityForView:(id)arg1;
- (struct CGSize)_vectorForFocusHeading:(unsigned long long)arg1;
- (id)_bestFocusCandidateForFocusHeading:(unsigned long long)arg1 currentFocusView:(id)arg2 direction:(struct CGSize)arg3 inView:(id)arg4;
- (id)_bestFocusCandidateStartingAtView:(id)arg1 inDirection:(struct CGSize)arg2 inView:(id)arg3;
- (void)_loadScrollViewContentInDirection:(struct CGSize)arg1 fromView:(id)arg2;
- (void)_updateScrollView:(id)arg1 visibleBounds:(struct CGRect)arg2;
- (void)_setFocusedView:(id)arg1;
- (int)_touchRegionForDigitizerLocation:(struct CGPoint)arg1;
- (void)_removeGestureRecognizers;
- (void)_addGestureRecognizers;
- (id)_focusedView;
- (void)_playTickSound;
- (void)_cleanupTickSound;
- (void)_setupTickSound;
- (void)_gestureRecognizerFailed:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)_handleTapGesture:(id)arg1;
- (void)_handlePanGesture:(id)arg1;
- (void)reset;
- (_Bool)moveInDirection:(unsigned long long)arg1;
- (_Bool)moveWithEvent:(id)arg1;
- (void)_handleButtonGesture:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

