//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIThreePartButton.h>

@class UIImage, UIImageView, UILabel;

__attribute__((visibility("hidden")))
@interface _UIMediaPushButton : UIThreePartButton
{
    UIImageView *_icon;
    UIImageView *_selectionMark;
    UILabel *_titleView;
    UIImage *_tableIcon;
    UIImage *_highlightedTableIcon;
}

@property(retain, nonatomic) UIImage *highlightedTableIcon; // @synthesize highlightedTableIcon=_highlightedTableIcon;
@property(retain, nonatomic) UIImage *tableIcon; // @synthesize tableIcon=_tableIcon;
@property(retain, nonatomic) UIImageView *selectionMark; // @synthesize selectionMark=_selectionMark;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (void)setupTextAttributes;
- (void)setHighlighted:(BOOL)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (void)_drawImageAndTextPartInRect:(struct CGRect)arg1;
- (void)setTitle:(id)arg1;

@end

