//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIImageView.h>

__attribute__((visibility("hidden")))
@interface _UINavigationBarBackIndicatorView : UIImageView
{
}

- (void)_willChangeToIdiom:(long long)arg1 onScreen:(id)arg2;
- (void)setAlpha:(double)arg1;

@end

