//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIImageView, UINavigationBar, _UIBackdropView, _UINavigationControllerPalette;

__attribute__((visibility("hidden")))
@interface _UINavigationPaletteBackground : UIView
{
    UIColor *_barTintColor;
    UIImageView *_shadowView;
    _UINavigationControllerPalette *_palette;
    UINavigationBar *_bar;
    _UIBackdropView *_adaptiveBackdrop;
    struct {
        unsigned int barTranslucence:3;
        unsigned int barStyle:3;
        unsigned int barWantsAdaptiveBackdrop:1;
    } _navbarFlags;
}

@property(retain, nonatomic, getter=_shadowView, setter=_setShadowView:) UIView *shadowView; // @synthesize shadowView=_shadowView;
- (void)didMoveToSuperview;
- (void)updateBackgroundView;
- (void)setBounds:(struct CGRect)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)_setFrame:(struct CGRect)arg1 forceUpdateBackgroundImage:(_Bool)arg2;
@property(nonatomic) _Bool barWantsAdaptiveBackdrop;
@property(nonatomic, getter=isTranslucent) _Bool translucent;
@property(nonatomic) long long barStyle;
@property(retain, nonatomic) UIColor *barTintColor;
- (void)dealloc;
- (void)_syncWithBarStyles;
- (id)initWithNavigationBar:(id)arg1 forPalette:(id)arg2;

@end

