//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/_UIRemoteViewController.h>

#import "_UIShareInvitationViewControllerHost.h"

@class NSExtension, NSString, _UISharingViewController;

__attribute__((visibility("hidden")))
@interface _UIShareInvitationRemoteViewController : _UIRemoteViewController <_UIShareInvitationViewControllerHost>
{
    _UISharingViewController *_publicController;
    NSExtension *_extension;
    id <NSCopying><NSObject> _extensionRequestIdentifier;
}

+ (id)exportedInterface;
+ (id)serviceViewControllerInterface;
@property(copy, nonatomic) id <NSCopying><NSObject> extensionRequestIdentifier; // @synthesize extensionRequestIdentifier=_extensionRequestIdentifier;
@property(retain, nonatomic) NSExtension *extension; // @synthesize extension=_extension;
@property(nonatomic) _UISharingViewController *publicController; // @synthesize publicController=_publicController;
- (void)_performHeaderActionWithCompletion:(CDUnknownBlockType)arg1;
- (void)_performAuxiliaryActionWithCompletion:(CDUnknownBlockType)arg1;
- (void)_tintColorDidChangeToColor:(id)arg1;
- (void)_shareWasMadePrivate;
- (void)_shareDidChange;
- (void)_dismissViewController;
- (void)viewDidLoad;
- (void)viewServiceDidTerminateWithError:(id)arg1;
- (void)invalidate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

