//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIControl, UIRemoveControl, UIView;

__attribute__((visibility("hidden")))
@interface _UITableCellTransientData : NSObject
{
    UIRemoveControl *_removeControl;
    UIControl *_grabber;
    UIView *_separator;
    unsigned int _reorderingEnabled:1;
    unsigned int _hidSeparatorForRemoveConfirmation:1;
    unsigned int _reserved:30;
}

- (BOOL)dataRequired;

@end

