//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, _UIViewAnimationAttributes;

@protocol _UIViewServiceImplicitAnimationDecodingProxy_EncodingProxyInterface
- (void)__animateNextInvocationOfSelector:(NSString *)arg1 withAnimationAttributes:(_UIViewAnimationAttributes *)arg2;
@end

