//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSValue;

@protocol _UIViewServiceTextEffectsOperator_RemoteViewControllerInterface
- (void)__hostViewWillDisappear:(BOOL)arg1;
- (void)__hostDidEnterBackground;
- (void)__hostWillEnterForeground;
- (void)__setNextAutomaticOrderOutDirection:(int)arg1 duration:(double)arg2;
- (void)__setContentSize:(NSValue *)arg1 windowOffset:(NSValue *)arg2;
- (void)__createHostedTextEffectsWithReplyHandler:(void (^)(id, NSError *))arg1;
@end

