//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "XPCProxyTarget.h"
#import "_UIViewServiceDeputyDelegate.h"

@class NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, XPCEndpoint, _UIAsyncInvocation, _UIViewServiceXPCListener;

__attribute__((visibility("hidden")))
@interface _UIViewServiceSession : NSObject <XPCProxyTarget, _UIViewServiceDeputyDelegate>
{
    _UIViewServiceXPCListener *_listener;
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_connectionHandlers;
    int _connectionHandlersLock;
    _UIAsyncInvocation *_invalidationInvocation;
    NSMutableSet *_deputies;
    NSMutableSet *_pendingConnectionCatchers;
    NSMutableSet *_pendingDeputyProxies;
    CDUnknownBlockType _terminationHandler;
    int __automatic_invalidation_retainCount;
    BOOL __automatic_invalidation_invalidated;
}

- (id)proxy:(id)arg1 detailedSignatureForSelector:(SEL)arg2;
- (void)_handleConnection:(id)arg1;
- (void)deputy:(id)arg1 didFailWithError:(id)arg2;
- (void)_invalidateUnconditionallyThen:(CDUnknownBlockType)arg1;
- (void)setTerminationHandler:(CDUnknownBlockType)arg1;
- (void)checkDeputyForRotation:(id)arg1;
- (void)unregisterDeputyType:(id)arg1;
- (void)registerDeputyType:(id)arg1 withConnectionHandler:(CDUnknownBlockType)arg2;
@property(readonly) XPCEndpoint *endpoint;
- (void)dealloc;
- (id)init;
- (BOOL)_isDeallocating;
- (BOOL)_tryRetain;
- (unsigned int)retainCount;
- (oneway void)release;
- (id)retain;
- (int)__automatic_invalidation_logic;

@end

