//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface AddressBookMatch : NSObject
{
    NSString *value;
    NSString *property;
    NSString *key;
    int identifier;
}

- (void)dealloc;
- (id)description;
- (id)initWithValue:(id)arg1 property:(id)arg2 key:(id)arg3 identifier:(int)arg4;

@end

