//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UIPopoverControllerDelegate.h"

@class NSArray, UIActivityViewController;

__attribute__((visibility("hidden")))
@interface UIActivityListViewController : UIViewController <UIPopoverControllerDelegate>
{
    NSArray *_activities;
    UIActivityViewController *_activityViewController;
}

@property(nonatomic) UIActivityViewController *activityViewController; // @synthesize activityViewController=_activityViewController;
@property(retain, nonatomic) NSArray *activities; // @synthesize activities=_activities;
- (void)dimStatusBar:(BOOL)arg1 animated:(BOOL)arg2;
- (void)setHeaderVisible:(BOOL)arg1;
- (void)reloadActivity:(id)arg1;
- (struct CGSize)contentSizeForViewInPopover;
- (unsigned int)supportedInterfaceOrientations;
- (void)viewWillDisappear:(BOOL)arg1;
- (void)viewWillAppear:(BOOL)arg1;
- (void)loadView;
- (void)dealloc;
- (id)initWithActivityViewController:(id)arg1 activities:(id)arg2;

@end

