//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSLayoutConstraint, UIActivityGroupCancelButton, UIActivityGroupView, UIControl, UIScrollView, UIView, _UIBackdropView;

__attribute__((visibility("hidden")))
@interface UIActivityGroupListViewController : UIViewController
{
    _Bool _darkStyleOnLegacyApp;
    _Bool _embedded;
    _Bool _modal;
    UIActivityGroupCancelButton *_cancelButton;
    _UIBackdropView *_backdropView;
    UIView *_contentView;
    UIView *_statusBlurView;
    NSLayoutConstraint *_statusBlurHeight;
    long long _currentStatusBarStyle;
    UIControl *_dimView;
    UIScrollView *_scrollView;
    UIActivityGroupView *_groupView;
}

@property(retain, nonatomic) UIActivityGroupView *groupView; // @synthesize groupView=_groupView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) UIControl *dimView; // @synthesize dimView=_dimView;
@property(nonatomic) long long currentStatusBarStyle; // @synthesize currentStatusBarStyle=_currentStatusBarStyle;
@property(retain, nonatomic) NSLayoutConstraint *statusBlurHeight; // @synthesize statusBlurHeight=_statusBlurHeight;
@property(retain, nonatomic) UIView *statusBlurView; // @synthesize statusBlurView=_statusBlurView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) _UIBackdropView *backdropView; // @synthesize backdropView=_backdropView;
@property(retain, nonatomic) UIActivityGroupCancelButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) _Bool modal; // @synthesize modal=_modal;
@property(nonatomic) _Bool embedded; // @synthesize embedded=_embedded;
@property(nonatomic) _Bool darkStyleOnLegacyApp; // @synthesize darkStyleOnLegacyApp=_darkStyleOnLegacyApp;
- (void)cancel;
- (void)showDone;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)hideDimmingView;
- (void)viewDidLayoutSubviews;
- (void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2;
- (long long)preferredStatusBarStyle;
- (double)displayHeight;
- (void)setActivityGroupViewControllers:(id)arg1;
- (void)updateVisibleActivityGroupViewControllers;
- (void)dealloc;
- (id)initWithActivityGroupViewControllers:(id)arg1 embedded:(_Bool)arg2 modal:(_Bool)arg3;

@end

