//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UIAutocorrectionRecord : NSObject
{
    NSString *_typing;
    NSString *_autocorrection;
}

+ (id)recordOfTyping:(id)arg1 forAutocorrection:(id)arg2;
@property(readonly, nonatomic) NSString *autocorrection; // @synthesize autocorrection=_autocorrection;
@property(readonly, nonatomic) NSString *typing; // @synthesize typing=_typing;
- (void)dealloc;

@end

