//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UILabel.h>

__attribute__((visibility("hidden")))
@interface UIButtonLabel : UILabel
{
    BOOL _reverseShadow;
}

- (void)setReverseShadow:(BOOL)arg1;
- (struct CGSize)shadowOffset;
- (void)setShadowOffset:(struct CGSize)arg1;
- (void)setLineBreakMode:(int)arg1;
- (void)setFont:(id)arg1;

@end

