//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIClassicController.h>

@interface UIClassicController (iAdsKnobs)
+ (id)sharedClassicController;
@property(nonatomic) BOOL drawsStatusBarFiller;
@property(nonatomic) BOOL masksToWindowBounds;
- (void)setZoomed:(BOOL)arg1 animated:(BOOL)arg2;

// Remaining properties
@property(nonatomic) BOOL drawsClassicChrome;
@property(nonatomic, getter=isZoomed) BOOL zoomed;
@end

