//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@interface UIControl (UIControlPrivate)
- (void)setTracking:(BOOL)arg1;
- (void)removeTarget:(id)arg1 forEvents:(int)arg2;
- (void)addTarget:(id)arg1 action:(SEL)arg2 forEvents:(int)arg3;
- (BOOL)hasOneOrMoreTargets;
- (BOOL)requiresDisplayOnTracking;
- (void)setRequiresDisplayOnTracking:(BOOL)arg1;
- (BOOL)touchDragged;
- (BOOL)shouldTrack;
@end

