//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIColor.h>

@interface UIColor (UIColorSystemColors)
+ (id)scrollViewTexturedBackgroundColor;
+ (id)underPageBackgroundColor;
+ (id)viewFlipsideBackgroundColor;
+ (id)groupTableViewBackgroundColor;
+ (id)darkTextColor;
+ (id)lightTextColor;
+ (id)insertionPointColor;
+ (id)selectionHighlightColor;
+ (id)pinStripeColor;
@end

