//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIImageAndTextTableCell.h>

__attribute__((visibility("hidden")))
@interface UIDateTableCell : UIImageAndTextTableCell
{
    float _horizontalOffset;
    float _verticalOffset;
}

- (void)layoutSubviews;
- (id)shadowColor;
- (struct CGRect)contentBounds;
- (void)setVerticalOffset:(float)arg1;
- (void)setHorizontalOffset:(float)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

