//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface UIDatePickerWeekMonthDayView : UIView
{
    UILabel *_dateLabel;
    UILabel *_weekdayLabel;
    float _weekdayWidth;
    struct {
        unsigned int weekdayLast:1;
    } _datePickerWeekMonthDayViewFlags;
}

@property(nonatomic) float weekdayWidth; // @synthesize weekdayWidth=_weekdayWidth;
@property(readonly, nonatomic) UILabel *weekdayLabel; // @synthesize weekdayLabel=_weekdayLabel;
@property(readonly, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(nonatomic) BOOL weekdayLast;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

