//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIDatePicker.h>

@interface UIDatePicker (UIDatePickerDeprecated)
- (void)setFrame:(struct CGRect)arg1;
- (void)setDate:(id)arg1 animate:(BOOL)arg2;
- (int)second;
- (int)minute;
- (int)hour;
- (void)setHighlightsToday:(BOOL)arg1;
- (void)setStaggerTimeIntervals:(BOOL)arg1;
- (void)setDateComponents:(id)arg1;
- (id)dateComponents;
- (double)timeInterval;
- (void)setTimeInterval:(double)arg1;
- (void)setDelegate:(id)arg1;
@end

