//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

__attribute__((visibility("hidden")))
@interface UIDatePickerContentView : UIView
{
    UILabel *_titleLabel;
    float _titleLabelMaxX;
    int _alignment;
    struct {
        unsigned int isAmPm:1;
    } _datePickerContentViewFlags;
}

@property(nonatomic) int titleAlignment; // @synthesize titleAlignment=_alignment;
@property(nonatomic) float titleLabelMaxX; // @synthesize titleLabelMaxX=_titleLabelMaxX;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void)layoutSubviews;
@property(nonatomic) BOOL isAmPm;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

