//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@class NSString;

@interface UIDevice (UIDevicePrivate)
+ (id)modelSpecificLocalizedStringKeyForKey:(id)arg1;
- (void)setIsWildcat:(BOOL)arg1;
- (BOOL)isWildcat;
- (BOOL)_isTTYEnabled;
- (void)_setBatteryLevel:(float)arg1;
- (void)_setBatteryState:(int)arg1;
- (void)_setProximityState:(BOOL)arg1;

// Remaining properties
@property(readonly, nonatomic) NSString *buildVersion;
@property(nonatomic) int orientation;
@end

