//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIDictationView.h>

#import "UIGestureRecognizerDelegate.h"

@class CADisplayLink;

__attribute__((visibility("hidden")))
@interface UIDictationFloatingView : UIDictationView <UIGestureRecognizerDelegate>
{
    CADisplayLink *_displayLink;
    struct CGPoint _velocity;
    struct CGPoint _target;
    BOOL _startedThrowAnimation;
    int _targetZone;
}

- (BOOL)allowsHorizontalTranslation;
- (void)endpointButtonPressed;
- (BOOL)gestureRecognizerShouldBegin:(id)arg1;
- (void)handlePanDetected:(id)arg1;
- (void)handlePanGestureFinished:(id)arg1;
- (void)startThrowAnimation;
- (void)updateThrowAnimation:(id)arg1;
- (void)setTransformForNewCenter:(struct CGPoint)arg1;
- (void)finishedThrowAnimation;
- (void)show;
- (struct CGPoint)positionForShow;
- (struct CGPoint)middleZonePosition;
- (void)returnToKeyboard;
- (void)snapToTargetZone:(int)arg1;
- (void)setTargetZone:(int)arg1;
- (struct CGPoint)transformedCenterOnscreen;
- (struct CGPoint)transformedCenter;
- (void)applicationEnteredBackground;
- (void)setInputViewsHiddenForDictation:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

