//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIDictationFloatingView.h>

__attribute__((visibility("hidden")))
@interface UIDictationAnchoredView : UIDictationFloatingView
{
}

+ (struct CGSize)layoutSize;
- (BOOL)allowsHorizontalTranslation;
- (struct CGPoint)contentOffset;
- (struct CGPoint)positionForShow;
- (void)show;
- (id)initWithFrame:(struct CGRect)arg1;

@end

