//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIEvent.h>

@interface UIEvent (UIEventPrivate)
- (int)_shakeState;
- (id)_touchesForGestureRecognizer:(id)arg1;
- (struct __GSEvent *)_gsEvent;
- (id)_initWithEvent:(struct __GSEvent *)arg1 touches:(id)arg2;
@end

