//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UIGroupInsertionItem : NSObject
{
    int _index;
    struct _NSRange _range;
}

- (struct _NSRange)range;
- (int)groupIndex;
- (id)initWithNewGroupBeforeGroup:(int)arg1 andRowCount:(int)arg2;
- (id)initWithExistingGroup:(int)arg1 andRowRange:(struct _NSRange)arg2;

@end

