//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIURLResolver.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface UIITunesStoreURLResolver : UIURLResolver
{
    NSArray *_converters;
}

+ (id)urlCacheChangedNotificationName;
+ (id)urlCacheName;
- (id)convertedURLForURL:(id)arg1;
- (void)dealloc;
- (id)initWithDictionary:(id)arg1;
- (id)_newURLConverterWithHostPatterns:(id)arg1 hostWhiteList:(id)arg2 pathPatterns:(id)arg3;

@end

