//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIKBCacheableView.h"

@class UIKBTree;

__attribute__((visibility("hidden")))
@interface UIKBKeyView : UIView <UIKBCacheableView>
{
    UIKBTree *m_keyboard;
    UIKBTree *m_key;
    int m_state;
    struct CGPoint m_drawOrigin;
    int m_clipCorners;
    struct __CFBoolean *m_allowsCaching;
}

@property(nonatomic) struct CGPoint drawOrigin; // @synthesize drawOrigin=m_drawOrigin;
@property(nonatomic) int clipCorners; // @synthesize clipCorners=m_clipCorners;
@property(readonly, nonatomic) int state; // @synthesize state=m_state;
@property(readonly, nonatomic) UIKBTree *key; // @synthesize key=m_key;
@property(readonly, nonatomic) UIKBTree *keyboard; // @synthesize keyboard=m_keyboard;
- (void)drawRect:(struct CGRect)arg1;
@property(readonly, nonatomic) float cachedWidth;
@property(readonly, nonatomic) BOOL cacheDeferable;
- (void)displayLayer:(id)arg1;
@property(readonly) BOOL shouldCache;
- (id)cacheKey;
- (int)textEffectsVisibilityLevel;
- (void)dealloc;
- (void)updateForKeyboard:(id)arg1 key:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 keyboard:(id)arg2 key:(id)arg3 state:(int)arg4;

@end

