//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

__attribute__((visibility("hidden")))
@interface UIKBKeyDisplayContents : NSObject
{
    _Bool _isCustomGlyph;
    _Bool _secondaryIsCustomGlyph;
    _Bool _fillPath;
    _Bool _force1xImages;
    _Bool _stringKeycapOverImage;
    NSString *_displayString;
    NSString *_displayStringImage;
    NSString *_secondaryDisplayStringImage;
    NSString *_secondaryDisplayString;
    NSArray *_variantDisplayContents;
    NSArray *_highlightedVariantsList;
    long long _displayPathType;
    UIKBKeyDisplayContents *_fallbackContents;
}

+ (id)displayContents;
@property(nonatomic) _Bool stringKeycapOverImage; // @synthesize stringKeycapOverImage=_stringKeycapOverImage;
@property(retain, nonatomic) UIKBKeyDisplayContents *fallbackContents; // @synthesize fallbackContents=_fallbackContents;
@property(nonatomic) _Bool force1xImages; // @synthesize force1xImages=_force1xImages;
@property(nonatomic) _Bool fillPath; // @synthesize fillPath=_fillPath;
@property(nonatomic) long long displayPathType; // @synthesize displayPathType=_displayPathType;
@property(retain, nonatomic) NSArray *highlightedVariantsList; // @synthesize highlightedVariantsList=_highlightedVariantsList;
@property(retain, nonatomic) NSArray *variantDisplayContents; // @synthesize variantDisplayContents=_variantDisplayContents;
@property(nonatomic) _Bool secondaryIsCustomGlyph; // @synthesize secondaryIsCustomGlyph=_secondaryIsCustomGlyph;
@property(nonatomic) _Bool isCustomGlyph; // @synthesize isCustomGlyph=_isCustomGlyph;
@property(retain, nonatomic) NSString *secondaryDisplayString; // @synthesize secondaryDisplayString=_secondaryDisplayString;
@property(retain, nonatomic) NSString *secondaryDisplayStringImage; // @synthesize secondaryDisplayStringImage=_secondaryDisplayStringImage;
@property(retain, nonatomic) NSString *displayStringImage; // @synthesize displayStringImage=_displayStringImage;
@property(retain, nonatomic) NSString *displayString; // @synthesize displayString=_displayString;
- (id)description;
- (void)dealloc;

@end

