//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIKBKey, UIKBKeyplane;

@interface UIKBKeyCacheEntry : NSObject
{
    UIKBKey *m_key;
    UIKBKeyplane *m_keyplane;
}

+ (id)entryWithKey:(id)arg1 keyPlane:(id)arg2;
@property(readonly, nonatomic) UIKBKeyplane *keyplane; // @synthesize keyplane=m_keyplane;
@property(readonly, nonatomic) UIKBKey *key; // @synthesize key=m_key;
- (id)initWithKey:(id)arg1 keyPlane:(id)arg2;

@end

