//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIDelayedAction, UIKBTree;

__attribute__((visibility("hidden")))
@interface UIKBDictationActivatorView : UIView
{
    UIDelayedAction *_timer;
    int _hitCount;
    UIKBTree *_dictationKey;
    BOOL _useShortenedDelayForNextRequestToActAsSpace;
}

+ (id)sharedInstance;
- (void)makeDictationKeyTemporarilyActAsSpace;
- (void)dictationFinishedFadeIn:(id)arg1 finished:(id)arg2;
- (void)activateDictationView:(id)arg1;
- (void)userTappedOnDictationKeyButGotSpaceKey;
- (id)hitTestAtPoint:(struct CGPoint)arg1;
- (void)setPressed:(BOOL)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

