//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class UIKBTree;

@protocol UIKeyboardRivenTransitionView
- (void)finishWithProgress:(double)arg1 completionBlock:(void (^)(void))arg2;
- (void)updateWithProgress:(double)arg1;
- (void)rebuildFromKeyplane:(UIKBTree *)arg1 toKeyplane:(UIKBTree *)arg2 keyboardType:(long long)arg3 orientation:(long long)arg4;

@optional
- (void)rebuildControlKeys:(int)arg1;
- (_Bool)canDisplayTransition;
@end

