//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIKeyboardCandidateScrollViewController;

@protocol UIKeyboardCandidateScrollViewControllerDelegate <NSObject>

@optional
- (void)padInlineFloatingViewExpand:(UIKeyboardCandidateScrollViewController *)arg1;
- (BOOL)padInlineFloatingViewIsExpanded:(UIKeyboardCandidateScrollViewController *)arg1;
- (NSArray *)indexTitlesForGroupTitles:(NSArray *)arg1;
- (NSArray *)groupedCandidatesForUnsortedCandidates:(NSArray *)arg1;
@end

