//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiCategoryController : NSObject
{
    id <UIKeyboardEmojiController> emojiController;
    NSMutableDictionary *categories;
    NSMutableDictionary *_defaultsData;
}

@property(retain) NSDictionary *defaultsData;
- (void)updateRecents;
- (id)categoryForKey:(id)arg1;
- (void)releaseCategories;
- (void)dealloc;
- (id)initWithController:(id)arg1;

@end

