//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIKeyboardCandidateArrowButton, UIKeyboardCandidateExtendedInputTextField;

__attribute__((visibility("hidden")))
@interface UIKeyboardCandidateExtendedInputView : UIView
{
    UIKeyboardCandidateExtendedInputTextField *_textField;
    UIKeyboardCandidateArrowButton *_arrowButton;
}

@property(retain, nonatomic) UIKeyboardCandidateArrowButton *arrowButton; // @synthesize arrowButton=_arrowButton;
@property(retain, nonatomic) UIKeyboardCandidateExtendedInputTextField *textField; // @synthesize textField=_textField;
- (void)setFrame:(struct CGRect)arg1;
- (void)layoutArrowButton;
- (void)drawRect:(struct CGRect)arg1;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

