//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardEmojiCategoriesControl.h>

@class NSArray;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmojiCategoriesControl_iPhone : UIKeyboardEmojiCategoriesControl
{
    NSArray *_selectedImages;
    NSArray *_unselectedImages;
}

- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)releaseImagesAndViews;
- (void)updateSegmentAndDividers:(int)arg1;
- (void)updateSegmentImages;

@end

