//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface UIKeyboardEmoji : NSObject
{
    NSString *name;
    NSString *imageName;
    unsigned short unicodeCharacter;
    NSString *codePoint;
    NSString *privateCodePoint;
    NSString *publicCodePoint;
}

+ (BOOL)shouldUsePublicCodePoints;
@property(retain) NSString *publicCodePoint; // @synthesize publicCodePoint;
@property(retain) NSString *privateCodePoint; // @synthesize privateCodePoint;
@property(retain) NSString *codePoint; // @synthesize codePoint;
@property unsigned short unicodeCharacter; // @synthesize unicodeCharacter;
@property(retain) NSString *imageName; // @synthesize imageName;
@property(retain) NSString *name; // @synthesize name;
@property(readonly) NSString *key;
- (void)dealloc;
- (id)image;
- (id)initWithName:(id)arg1 imageName:(id)arg2 codePoint:(unsigned short)arg3;

@end

