//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol UIKeyboardSplitTransitionDelegate
- (void)transitionDidFinish:(_Bool)arg1;
- (void)transitionDidFinish;
- (void)updateFrame:(struct CGRect)arg1 withProgress:(double)arg2 withDuration:(double)arg3 splitHeightDelta:(double)arg4;
- (void)updateFrame:(struct CGRect)arg1 withDuration:(double)arg2 splitHeightDelta:(double)arg3;
@end

