//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardInputManager.h>

@interface UIKeyboardInputManager (ShortcutConversion)
- (id)shortcutConversionForInput:(id)arg1 andExistingString:(id)arg2 existingStringStartsInMiddleOfWord:(BOOL)arg3;
- (unsigned int)maximumShortcutLengthAllowed;
- (BOOL)supportsShortcutConversion;
@end

