//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIKeyboardCandidate.h>

@class NSString;

@interface UIKeyboardCandidateSingle : UIKeyboardCandidate
{
    NSString *_candidate;
}

@property(copy, nonatomic) NSString *candidate; // @synthesize candidate=_candidate;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)dealloc;
- (id)initWithCandidate:(id)arg1;

@end

