//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIMenuController.h>

@interface UIMenuController (UIMenuControllerStatic)
- (BOOL)_updateAnimated:(BOOL)arg1 checkVisible:(BOOL)arg2;
@end

