//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UINavigationBar;

__attribute__((visibility("hidden")))
@interface UINavBarPrompt : UIView
{
    NSString *_prompt;
    UINavigationBar *_navBar;
}

- (void)setFrame:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (struct CGRect)promptBounds;
- (id)prompt;
- (void)setPrompt:(id)arg1;
- (void)dealloc;
- (void)clearWeakReference:(id)arg1;
- (id)initWithPrompt:(id)arg1 navBar:(id)arg2;

@end

