//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIPageControl.h>

@interface UIPageControl (Internal)
- (void)_updateCurrentPageDisplay;
- (void)_setCurrentPage:(int)arg1;
- (int)_displayedPage;
- (void)_setDisplayedPage:(int)arg1;
@end

