//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSAttributedString, NSString, UILabel;

__attribute__((visibility("hidden")))
@interface UIPickerTableViewTitledCell : UITableViewCell
{
    UILabel *_titleLabel;
}

@property(retain, nonatomic) NSAttributedString *attributedTitle;
@property(retain, nonatomic) NSString *title;
- (id)initWithStyle:(int)arg1 reuseIdentifier:(id)arg2;

@end

