//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIView;

__attribute__((visibility("hidden")))
@interface UIPickerTableViewWrapperCell : UITableViewCell
{
    UIView *_wrappedView;
    struct CGSize _wrappedViewSize;
}

- (void)prepareForReuse;
- (void)resizeSubviewsWithOldSize:(struct CGSize)arg1;
@property(retain, nonatomic) UIView *wrappedView;
- (void)_updateWrappedView;
- (void)_updateWrappedViewFrame;
- (id)initWithFrame:(struct CGRect)arg1;

@end

