//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIRemoveControl.h>

__attribute__((visibility("hidden")))
@interface UIPreferencesTableCellRemoveControl : UIRemoveControl
{
}

- (struct CGRect)targetContentBounds;
- (float)_removeConfirmationButtonVerticalOffset;
- (float)_verticalOffsetFromTarget;
- (struct CGRect)removeButtonStartingFrame;
- (struct CGRect)removeButtonEndingFrame;
- (float)removeButtonAnimationDuration;
- (void)addConfirmationButtonSubview:(id)arg1 withWidth:(float)arg2 target:(id)arg3;

@end

