//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSString, UIActivityIndicatorView, UILabel, UIView;

__attribute__((visibility("hidden")))
@interface UIPrintStatusTableViewCell : UITableViewCell
{
    UILabel *_hostLabel;
    UIView *_verticalBar;
    UIActivityIndicatorView *_activityIndicator;
}

- (void)layoutSubviews;
@property(nonatomic) BOOL showActive;
@property(copy, nonatomic) NSString *hostName;
- (void)dealloc;
- (id)initWithReuseIdentifier:(id)arg1;

@end

