//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIBezierPath, UIColor;

__attribute__((visibility("hidden")))
@interface UIRoundedRectButton : UIButton
{
    UIBezierPath *_fillPath;
    UIColor *_fillColor;
    UIColor *_tintColor;
}

- (id)tintColor;
- (void)drawRect:(struct CGRect)arg1;
- (void)setTintColor:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (int)buttonType;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)setFrame:(struct CGRect)arg1;
- (void)_invalidatePaths;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 fillColor:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)_commonRoundedRectButtonInit;

@end

