//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIAnimation.h>

__attribute__((visibility("hidden")))
@interface UIScrollerScrollAnimation : UIAnimation
{
    struct CGPoint _originalOffset;
    struct CGPoint _targetOffset;
}

- (void)setProgress:(float)arg1;
- (void)setOriginalOffset:(struct CGPoint)arg1;
- (void)setTargetOffset:(struct CGPoint)arg1;
- (struct CGPoint)targetOffset;

@end

