//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class CADisplayLink, NSString;

__attribute__((visibility("hidden")))
@interface UIScrollTestParameters : NSObject
{
    int _iterations;
    int _yDelta;
    int _scrollLength;
    NSString *_currentTest;
    CADisplayLink *_displayLink;
}

@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(nonatomic) int scrollLength; // @synthesize scrollLength=_scrollLength;
@property(nonatomic) int yDelta; // @synthesize yDelta=_yDelta;
@property(retain, nonatomic) NSString *currentTest; // @synthesize currentTest=_currentTest;
@property(nonatomic) int iterations; // @synthesize iterations=_iterations;
- (void)dealloc;
- (id)initWithName:(id)arg1 iterations:(int)arg2 delta:(int)arg3 length:(int)arg4;

@end

