//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITextField.h>

@interface UISearchField : UITextField
{
}

+ (float)defaultHeight;
- (BOOL)_shouldSendContentChangedNotificationsIfOnlyMarkedTextChanged;
- (id)_scriptingInfo;
- (Class)_systemBackgroundViewClass;
- (struct CGRect)rightViewRectForBounds:(struct CGRect)arg1;
- (struct CGRect)_textRectExcludingButtonsForBounds:(struct CGRect)arg1;
- (struct CGRect)iconRect;
- (id)initWithFrame:(struct CGRect)arg1;

@end

