//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITextTapRecognizer.h>

@class UIView<UITextSelectingContainer>;

__attribute__((visibility("hidden")))
@interface UISelectionTapRecognizer : UITextTapRecognizer
{
    UIView<UITextSelectingContainer> *_textView;
}

@property UIView<UITextSelectingContainer> *textView; // @synthesize textView=_textView;
- (void)setState:(int)arg1;
- (BOOL)isCloseToSelection;

@end

