//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UISegmentedControl.h>

@interface UISegmentedControl (Static)
- (void)_removeSegmentAnimationFinished:(id)arg1 finished:(id)arg2 context:(void *)arg3;
- (void)_clearSelectedSegment;
- (void)_insertSegment:(int)arg1 withInfo:(id)arg2 animated:(BOOL)arg3;
- (void)_createSegmentAtIndex:(int)arg1 position:(unsigned int)arg2 withInfo:(id)arg3;
- (BOOL)_isInMiniBar;
- (float)_barHeight;
@end

