//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableView.h>

@class UISearchDisplayController;

@interface UISearchResultsTableView : UITableView
{
    UISearchDisplayController *_controller;
}

@property(nonatomic) UISearchDisplayController *controller; // @synthesize controller=_controller;
- (float)_offsetForNoResultsMessage;
- (void)_numberOfRowsDidChange;
- (void)setContentOffset:(struct CGPoint)arg1;

@end

