//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface UISharedImageStatisticsTable : NSObject
{
    NSMutableDictionary *_statistics;
}

- (id)statisticsForImageWithName:(id)arg1;
- (id)allImageNames;
- (void)noteImageWithNameWasFlushed:(id)arg1;
- (void)noteImageWithNameWasRequested:(id)arg1;
- (void)clearStatistics;
- (void)dealloc;
- (id)init;

@end

