//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UIStoryboardSegue : NSObject
{
    NSString *_identifier;
    id _sourceViewController;
    id _destinationViewController;
}

@property(readonly, nonatomic) id destinationViewController; // @synthesize destinationViewController=_destinationViewController;
@property(readonly, nonatomic) id sourceViewController; // @synthesize sourceViewController=_sourceViewController;
@property(readonly, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void)perform;
- (id)initWithIdentifier:(id)arg1 source:(id)arg2 destination:(id)arg3;
- (void)dealloc;

@end

