//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIStatusBarItemView.h>

__attribute__((visibility("hidden")))
@interface UIStatusBarBatteryItemView : UIStatusBarItemView
{
    int _capacity;
    int _state;
}

- (float)extraRightPadding;
- (id)contentsImageForStyle:(int)arg1;
- (BOOL)updateForNewData:(id)arg1 actions:(int)arg2;

@end

