//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UISwitch.h>

@class UIColor;

@interface UISwitch (UISwitchPrivate)
- (void)setAlternateColors:(BOOL)arg1;

// Remaining properties
@property(retain, nonatomic, getter=_onColor, setter=_setOnColor:) UIColor *onColor;
@end

