//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITabBarCustomizeView.h>

__attribute__((visibility("hidden")))
@interface UITabBarCustomizeViewLegacy : UITabBarCustomizeView
{
}

- (void)tabBarMouseUp:(struct __GSEvent *)arg1;
- (void)tabBarMouseDragged:(struct __GSEvent *)arg1;
- (void)tabBarMouseDown:(struct __GSEvent *)arg1;
- (void)mouseUp:(struct __GSEvent *)arg1;
- (void)mouseDragged:(struct __GSEvent *)arg1;
- (void)mouseDown:(struct __GSEvent *)arg1;
- (id)_fakeTouchesForEvent:(struct __GSEvent *)arg1 view:(id)arg2;
- (id)_fakeEventForEvent:(struct __GSEvent *)arg1 touches:(id)arg2;

@end

