//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UITableViewIndex.h>

@interface UITableViewIndex (UITableViewIndex_LegacyEventSystemSupport)
- (void)mouseUp:(struct __GSEvent *)arg1;
- (void)mouseDragged:(struct __GSEvent *)arg1;
- (void)mouseDown:(struct __GSEvent *)arg1;
- (id)_createTouchesWithMouseEvent:(struct __GSEvent *)arg1 phase:(int)arg2;
@end

