//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIToolbar.h>

@interface UIToolbar (UIButtonBarButtonItem)
- (id)initInView:(id)arg1 withItems:(CDStruct_dbaf35c5 *)arg2 withCount:(int)arg3;
- (id)initInView:(id)arg1 withFrame:(struct CGRect)arg2 withItems:(CDStruct_dbaf35c5 *)arg3 withCount:(int)arg4;
@end

