//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface UIView (UIViewGestures)
- (void)removeAllGestureRecognizers;
- (void)removeGestureRecognizer:(id)arg1;
- (void)addGestureRecognizer:(id)arg1;
@property(nonatomic) BOOL deliversTouchesForGesturesToSuperview;
@property(nonatomic) BOOL gesturesEnabled;
- (void)setGestureRecognizers:(id)arg1;
- (id)gestureRecognizers;
@end

