//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "WebFrame.h"

@interface WebFrame (BrowserAdditions)
- (BOOL)isOrphaned;
- (BOOL)containsAnyFocusedFormFields;
- (BOOL)containsAnyFormFields;
- (id)allFormFields;
- (void)_collectFormFieldElementsIntoArray:(id)arg1 upToLimit:(unsigned int)arg2 onlyIncludeFocusedElements:(BOOL)arg3;
- (id)_topFrame;
- (BOOL)isMainFrame;
@end

